/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyRegistrationAppOwnerRequest {
  companyAddress: string;
  companyAdminId: number;
  companyCity: string;
  companyEmail: string;
  companyName: string;
  companyPaymentPosition: 'WEEKLY' | 'BIWEEKLY';
  companyPhone: string;
  companyState: string;
  companyStateIdNumber: string;
  companyZipCode: string;
  defaultMemo: string;
  employerEIN: string;
  experienceModRate: number;
  fundingAccountNumber: string;
  fundingBankName: string;
  fundingRoutingNumber: string;
  returnMailingAddress: string;
  signatureName: string;
  signatureTitle: string;
  socialSecurityTaxForCompany: number;
  specialTwoCharConditionCodeForMTA305: string;
  wcInsuranceCarrier: string;
  wcPolicyNumber: string;
}
