/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyResponse {
  companyAddress?: string;
  companyEmail?: string;
  companyId?: number;
  companyName?: string;
  companyPhone?: string;
  monthlySubscription?: number;
  pricePerEmployee?: number;
  subscriptionStatus?: string;
  workersQuantity?: number;
}
