/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyTaxCalculationResponse {
  calculationDate?: string;
  companyId?: number;
  companyName?: string;
  employeeCount?: number;
  federalUnemploymentTax?: number;
  medicareTax?: number;
  monthlyIncome?: number;
  nyDisabilityInsurance?: number;
  nyUnemploymentTax?: number;
  socialSecurityTax?: number;
  totalPayroll?: number;
  totalTaxes?: number;
  workersCompensation?: number;
}
