/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyStripeResponse {
  companyId?: number;
  monthlySubscription?: number;
  pricePerEmployee?: number;
  stripeBasePriceId?: string;
  stripeSeatsPriceId?: string;
  subscriptionCurrentPeriodEnd?: string;
  subscriptionStatus?: string;
  workersQuantity?: number;
}
