/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyUpdatingRequest {
  companyAddress: string;
  companyEmail: string;
  companyName: string;
  companyPhone: string;
  workersQuantity: number;
}
