/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactSalesFormResponse {
  firstName?: string;
  id?: number;
  lastName?: string;
  phoneNumber?: string;
}
