/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSubscriptionRequest {
  companyId: number;
  monthlySubscription: number;
  pricePerEmployee: number;
}
