/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface DailyScheduleResponse {
  date?: string;
  dayOfWeek?: string;
  endTime?: LocalTime;
  hoursWorked?: number;
  isOnDuty?: boolean;
  startTime?: LocalTime;
  workSiteName?: string;
}
