/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface DaySchedule {
  endTime: LocalTime;
  isCompanyPayingLunch: boolean;
  isDayOff?: boolean;
  lunchEnd: LocalTime;
  lunchStart: LocalTime;
  startTime: LocalTime;
}
