/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmployeeSutaDto {
  employeeName?: string;
  exceededLimit?: boolean;
  grossWages?: number;
  sutaTax?: number;
  sutaWageBase?: number;
}
