/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DailyFinanceInfo } from '../models/daily-finance-info';
export interface FinanceInfoForWeekInFinanceScreenResponse {
  dailyInfo?: Array<DailyFinanceInfo>;
  periodEnd?: string;
  periodStart?: string;
  totalGrossPay?: number;
  totalHoursWorked?: number;
  totalNetPay?: number;
}
