/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IsWithinRadiusResponse {
  actualLatitude?: number;
  actualLongitude?: number;
  allowedRadius?: number;
  providedLatitude?: number;
  providedLongitude?: number;
  withinRadius?: boolean;
  worksiteId?: number;
}
