/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationUpdateDto {
  accuracy?: number;
  altitude?: number;
  batteryLevel?: number;
  bearing?: number;
  latitude: number;
  longitude: number;
  provider?: string;
  speed?: number;
  timestamp: string;
}
