/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorksiteWorkerResponse } from '../models/worksite-worker-response';
export interface PageResponseWorksiteWorkerResponse {
  content?: Array<WorksiteWorkerResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
