/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TermsOfUseRequestDataResponse } from '../models/terms-of-use-request-data-response';
export interface PageResponseTermsOfUseRequestDataResponse {
  content?: Array<TermsOfUseRequestDataResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
