/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactSalesFormResponse } from '../models/contact-sales-form-response';
export interface PageResponseContactSalesFormResponse {
  content?: Array<ContactSalesFormResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
