/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotesForPunchResponse } from '../models/notes-for-punch-response';
export interface PageResponseNotesForPunchResponse {
  content?: Array<NotesForPunchResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
