/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PayStubFileDto {
  downloadUrl?: string;
  employeeName?: string;
  fileName?: string;
  fileSize?: number;
  payrollId?: number;
  periodEnd?: string;
  periodStart?: string;
}
