/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PunchOutResponse {
  checkInTime?: string;
  checkOutLatitude?: number;
  checkOutLongitude?: number;
  checkOutPhotoUrl?: string;
  checkOutTime?: string;
  formattedCheckInTime?: string;
  formattedCheckOutTime?: string;
  hoursWorked?: number;
  isSuccessful?: boolean;
  message?: string;
  overtimeHours?: number;
  workSiteAddress?: string;
  workSiteId?: number;
  workSiteName?: string;
  workerFullName?: string;
  workerId?: number;
}
