/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PunchInResponse {
  checkInLatitude?: number;
  checkInLocation?: string;
  checkInLongitude?: number;
  checkInPhotoUrl?: string;
  checkInTime?: string;
  formattedCheckInTime?: string;
  isSuccessful?: boolean;
  message?: string;
  notesForPunchIn?: string;
  workSiteAddress?: string;
  workSiteId?: number;
  workSiteName?: string;
  workerFullName?: string;
  workerId?: number;
}
