/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuarterlySutaDto {
  grossWages?: number;
  isLiable?: boolean;
  quarter?: number;
  quarterEnd?: string;
  quarterStart?: string;
  sutaTaxOwed?: number;
  sutaTaxPaid?: number;
  sutaWageBase?: number;
}
