/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RandonAttendanceVerificationRequest {
  latitude: number;
  longitude: number;
  photoBase64: string;
  verificationId: number;
  workSiteId?: number;
}
