/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RandonAttendanceVerificationResponse {
  formattedRandomAttendanceVerificationTime?: string;
  isMissed?: boolean;
  isMissedMessage?: string;
  isSuccessful?: boolean;
  message?: string;
  randomAttendanceVerificationLatitude?: number;
  randomAttendanceVerificationLocation?: string;
  randomAttendanceVerificationLongitude?: number;
  randomAttendanceVerificationPhotoUrl?: string;
  randomAttendanceVerificationTime?: string;
  verificationId?: number;
  workSiteAddress?: string;
  workSiteId?: number;
  workSiteName?: string;
  workerFullName?: string;
  workerId?: number;
}
