/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DependentsRequest } from '../models/dependents-request';
import { I9DocumentRequest } from '../models/i-9-document-request';
export interface RegistrationAdminRequest {
  adjustmentsSchedule1?: number;
  apt: string;
  city: string;
  coverageStartDate?: string;
  dateOfBirth: string;
  dateWhenRehired?: string;
  deductions?: number;
  dependents: number;
  dependentsList: Array<DependentsRequest>;
  dependentsUnder17?: number;
  email: string;
  employmentType: 'W2' | 'CONTRACTOR_1099';
  enrolledInHealthPlan?: boolean;
  estimatedItemizedDeductions?: number;
  exemptFromWithholding: boolean;
  extraWithHoldings: number;
  filingStatus: 'SINGLE' | 'HEAD_OF_HOUSEHOLD' | 'MARRIED_FILLING_SEPARATELY' | 'MARRIED_FILLING_JOINTLY';
  firstName: string;
  formI94AdmissionNumber?: string;
  gender: 'MALE' | 'FEMALE' | 'OTHER';
  homeAddress: string;
  i9Documents?: Array<I9DocumentRequest>;
  isANonCitizen?: boolean;
  isCitizen?: boolean;
  isNonCitizenNationalOfTheUS?: boolean;
  isPermanentResident?: boolean;
  isRehired?: boolean;
  lastName: string;
  livesInNYC: boolean;
  middleInitial?: string;
  monthlyHealthPremium?: number;
  multipleJobsAdditionalWithholding?: number;
  multipleJobsOrSpouseWorks: boolean;
  multipleJobsWorksheetLine2a?: number;
  multipleJobsWorksheetLine2b?: number;
  otherDependents?: number;
  otherIncome?: number;
  passportCountryOfIssuance?: string;
  passportNumber?: string;
  password: string;
  payFrequency: 'WEEKLY' | 'BIWEEKLY' | 'MONTHLY';
  phoneNumber: string;
  ssn_WORKER?: string;
  state: string;
  totalDependentsCredit?: number;
  twoJobsCheckBox: boolean;
  uscisNumber?: string;
  wcRiskClassCode?: string;
  workAuthorizationExpiryDate?: string;
  zipcode: string;
}
