/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  companyAddress: string;
  companyName: string;
  dateOfBirth?: string;
  email: string;
  firstName: string;
  gender: 'MALE' | 'FEMALE' | 'OTHER';
  homeAddress: string;
  lastName: string;
  password: string;
  phoneNumber: string;
  ssn_WORKER?: string;
}
