/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RelatedUserInCompanyResponse {
  baseHourlyRate?: number;
  companyId?: number;
  email?: string;
  firstName?: string;
  lastName?: string;
  workerId?: number;
}
