/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportFileDto {
  createdDate?: string;
  fileName?: string;
  fileSize?: number;
  key?: string;
  periodType?: string;
  reportType?: string;
  url?: string;
}
