/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface ScheduleDto {
  dayOfWeek?: 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';
  endTime?: LocalTime;
  isCompanyPayingLunch?: boolean;
  isDayOff?: boolean;
  lunchEnd?: LocalTime;
  lunchStart?: LocalTime;
  scheduleId?: number;
  startTime?: LocalTime;
}
