/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SelectWorkSiteResponse {
  selectedWorkSiteId?: number;
  selectedWorkSiteName?: string;
  workerId?: number;
}
