/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SetNewCustomRadiusForWorkerInSpecialWorkSiteResponse {
  companyName?: string;
  firstName?: string;
  lastName?: string;
  newRadius?: number;
  workSiteId?: number;
  workerId?: number;
}
