/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsEmailRequest {
  confirmNewEmail: string;
  currentEmail: string;
  newEmail: string;
}
