/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsPhoneNumberRequest {
  confirmNewPhoneNumber?: string;
  currentPhoneNumber?: string;
  newPhoneNumber?: string;
}
