/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeSutaDto } from '../models/employee-suta-dto';
import { QuarterlySutaDto } from '../models/quarterly-suta-dto';
export interface SutaReportDto {
  companyAddress?: string;
  companyCity?: string;
  companyId?: number;
  companyName?: string;
  companyPhone?: string;
  companyState?: string;
  companyZipCode?: string;
  complianceStatus?: boolean;
  employeeDetails?: Array<EmployeeSutaDto>;
  employeesSubjectToSuta?: number;
  employerEIN?: string;
  experienceRate?: number;
  needsPayment?: boolean;
  nextPaymentDue?: string;
  notes?: Array<string>;
  periodEnd?: string;
  periodStart?: string;
  quarter?: number;
  quarterlyBreakdown?: Array<QuarterlySutaDto>;
  remainingSutaLiability?: number;
  reportType?: string;
  standardSutaRate?: number;
  sutaAccountNumber?: string;
  sutaRate?: number;
  taxYear?: number;
  totalEmployees?: number;
  totalGrossWages?: number;
  totalSutaTaxOwed?: number;
  totalSutaTaxPaid?: number;
  totalSutaWageBase?: number;
}
