/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TermsOfUseRequestDataResponse {
  device?: string;
  event?: string;
  id?: number;
  ip?: string;
  osVersion?: string;
  privacyVersion?: string;
  termsVersion?: string;
  timeStamp?: string;
  userId?: number;
}
