/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TermsOfUseRequestDataRequest {
  device?: string;
  event?: string;
  id?: number;
  ip?: string;
  osVersion?: string;
  privacyVersion?: string;
  termsVersion?: string;
  userId?: number;
}
