/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransferResponse {
  formattedTransferTime?: string;
  isSuccessful?: boolean;
  message?: string;
  transferLatitude?: number;
  transferLocation?: string;
  transferLongitude?: number;
  transferPhotoUrl?: string;
  transferTime?: string;
  workSiteAddress?: string;
  workSiteId?: number;
  workSiteName?: string;
  workerFullName?: string;
  workerId?: number;
}
