/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePunchInForWorkerResponse {
  current_work_site?: string;
  newPunchInTime?: string;
  workerFullName?: string;
  workerId?: number;
}
