/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface UpdatePunchForWorkerRequest {
  newPunchDate: string;
  newPunchTime: LocalTime;
  notes: string;
  punchType: 'PUNCH_IN' | 'PUNCH_OUT';
  skipOvertimeCalculation: boolean;
  workSiteId: number;
  workedHours: number;
}
