/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface UpdatePunchForWorkerResponse {
  hoursWorked?: number;
  isSuccessful?: boolean;
  message?: string;
  newPunchDate?: string;
  newPunchTime?: LocalTime;
  overtimeHours?: number;
  periodEnd?: string;
  periodStart?: string;
  punchType?: 'PUNCH_IN' | 'PUNCH_OUT';
  workSiteName?: string;
  workerId?: number;
  workerName?: string;
}
