/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserFullContactInformation {
  address?: string;
  email?: string;
  fullName?: string;
  phoneNumber?: string;
  photoFileName?: string;
  photoUrl?: string;
}
