/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocalTime } from '../models/local-time';
export interface WorkSiteRequest {
  address: string;
  allowedRadius: number;
  latitude: number;
  longitude: number;
  workDayEnd: LocalTime;
  workDayStart: LocalTime;
  workSiteName: string;
}
