/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DaySchedule } from '../models/day-schedule';
export interface WorkerSetScheduleRequest2 {
  weeklySchedule: {
[key: string]: DaySchedule;
};
}
