/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkerHourResponse {
  overtimeHours?: number;
  regularHours?: number;
  totalHours?: number;
}
