/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkSiteClosedDaysResponse {
  closedDays?: Array<string>;
  siteAddress?: string;
  siteName?: string;
  workSiteId?: number;
}
