/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduleDto } from '../models/schedule-dto';
export interface WorkSchedulerResponse {
  message?: string;
  schedules?: Array<ScheduleDto>;
  workerId?: number;
  workerName?: string;
}
