/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkerPersonalInformationResponse {
  address?: string;
  baseHourlyRate?: number;
  companyId?: number;
  companyName?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  workerId?: number;
}
