/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkerPhotosResponse {
  checkInPhotoUrl?: string;
  checkInTime?: string;
  checkOutPhotoUrl?: string;
  checkOutTime?: string;
  date?: string;
  workerId?: number;
  workerName?: string;
}
