/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkSiteUpdateLocationResponse {
  newLatitude?: number;
  newLongitude?: number;
  newRadius?: number;
  workSiteId?: number;
}
