/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RandonAttendanceVerificationResponse } from '../../models/randon-attendance-verification-response';

export interface GetPendingVerification$Params {
}

export function getPendingVerification(http: HttpClient, rootUrl: string, params?: GetPendingVerification$Params, context?: HttpContext): Observable<StrictHttpResponse<RandonAttendanceVerificationResponse>> {
  const rb = new RequestBuilder(rootUrl, getPendingVerification.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RandonAttendanceVerificationResponse>;
    })
  );
}

getPendingVerification.PATH = '/remote-worker/pending-verification';
