/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkerSetScheduleRequest2 } from '../../models/worker-set-schedule-request-2';
import { WorkSchedulerResponse } from '../../models/work-scheduler-response';

export interface SetWeeklySchedule$Params {
  workerId: number;
      body: WorkerSetScheduleRequest2
}

export function setWeeklySchedule(http: HttpClient, rootUrl: string, params: SetWeeklySchedule$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkSchedulerResponse>> {
  const rb = new RequestBuilder(rootUrl, setWeeklySchedule.PATH, 'post');
  if (params) {
    rb.path('workerId', params.workerId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkSchedulerResponse>;
    })
  );
}

setWeeklySchedule.PATH = '/schedule/set-schedule/{workerId}';
