/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RelatedUserInCompanyResponse } from '../../models/related-user-in-company-response';

export interface FindCertainEmployeeInCompany$Params {
  workerId: number;
  companyId: number;
}

export function findCertainEmployeeInCompany(http: HttpClient, rootUrl: string, params: FindCertainEmployeeInCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<RelatedUserInCompanyResponse>> {
  const rb = new RequestBuilder(rootUrl, findCertainEmployeeInCompany.PATH, 'get');
  if (params) {
    rb.path('workerId', params.workerId, {});
    rb.path('companyId', params.companyId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RelatedUserInCompanyResponse>;
    })
  );
}

findCertainEmployeeInCompany.PATH = '/company/employee-in-certain-company/{workerId}/{companyId}/';
