/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyIncomePerMonthRequest } from '../../models/company-income-per-month-request';
import { CompanyIncomePerMonthResponse } from '../../models/company-income-per-month-response';

export interface SetCompanyIncomePerMonth$Params {
  companyId: number;
      body: CompanyIncomePerMonthRequest
}

export function setCompanyIncomePerMonth(http: HttpClient, rootUrl: string, params: SetCompanyIncomePerMonth$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyIncomePerMonthResponse>> {
  const rb = new RequestBuilder(rootUrl, setCompanyIncomePerMonth.PATH, 'put');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyIncomePerMonthResponse>;
    })
  );
}

setCompanyIncomePerMonth.PATH = '/company/{companyId}/income';
