/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateCompanyNameRequest } from '../../models/update-company-name-request';
import { UpdateCompanyNameResponse } from '../../models/update-company-name-response';

export interface UpdateCompanyName$Params {
      body: UpdateCompanyNameRequest
}

export function updateCompanyName(http: HttpClient, rootUrl: string, params: UpdateCompanyName$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateCompanyNameResponse>> {
  const rb = new RequestBuilder(rootUrl, updateCompanyName.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateCompanyNameResponse>;
    })
  );
}

updateCompanyName.PATH = '/company/update-name';
