/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyUpdatingRequest } from '../../models/company-updating-request';
import { CompanyUpdatingResponse } from '../../models/company-updating-response';

export interface UpdateCompany$Params {
  companyId: number;
      body: CompanyUpdatingRequest
}

export function updateCompany(http: HttpClient, rootUrl: string, params: UpdateCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyUpdatingResponse>> {
  const rb = new RequestBuilder(rootUrl, updateCompany.PATH, 'put');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyUpdatingResponse>;
    })
  );
}

updateCompany.PATH = '/company/{companyId}';
