# Основная конфигурация Alertmanager
global:
  # SMTP настройки для Gmail
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'mishamay583@gmail.com'  # Замени на свой email
  smtp_auth_username: 'mishamay583@gmail.com'  # Замени на свой email
  smtp_auth_password: 'wwex oisw bwnc uuvy'  # App Password (НЕ обычный пароль!)
  smtp_require_tls: true

receivers:
  # Канал для критических алертов
  - name: 'critical-alerts'
    email_configs:
      - to: 'mishamay583@gmail.com'  # Куда отправлять
        send_resolved: true
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} - FaceCheck Production'
        html: |
          <h2>🚨 Critical Alert</h2>
          <p><b>Alert:</b> {{ .GroupLabels.alertname }}</p>
          <p><b>Instance:</b> {{ .CommonLabels.instance }}</p>
          <p><b>Severity:</b> {{ .CommonLabels.severity }}</p>
          <h3>Description:</h3>
          {{ range .Alerts }}
            <p>{{ .Annotations.description }}</p>
          {{ end }}
          <p><b>Time:</b> {{ .Alerts.StartsAt }}</p>
  

  # Канал для предупреждений
  - name: 'warning-alerts'
    email_configs:
      - to: 'mishamay583@gmail.com'
        send_resolved: true
        headers:
          Subject: '⚠️ WARNING: {{ .GroupLabels.alertname }} - FaceCheck'

  # Канал для бизнес-алертов
  - name: 'business-alerts'
    email_configs:
      - to: 'mishamay583@gmail.com@gmail.com'
        send_resolved: true
        headers:
          Subject: '📊 Business Alert: {{ .GroupLabels.alertname }}'

# Настройка маршрутизации алертов
route:
  # Группировка алертов
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  # Дефолтный получатель
  receiver: 'warning-alerts'

  # Маршруты для разных типов алертов
  routes:
    # Критические алерты - сразу отправляем
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 1h

    # Бизнес алерты
    - match:
        team: business
      receiver: 'business-alerts'
      group_wait: 5m
      repeat_interval: 6h

    # Security алерты
    - match:
        team: security
      receiver: 'critical-alerts'
      group_wait: 10s

# Подавление дублирующихся алертов
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']