
services:
  postgresql:
    container_name: fc_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: misha
      POSTGRES_PASSWORD: misha
      POSTGRES_DB: face_check      # ← вот это
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: fc-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-net


  prometheus:
    image: prom/prometheus:latest
    container_name: fc-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - microservices-net


  grafana:
    image: grafana/grafana:latest
    container_name: fc-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - microservices-net
    depends_on:
      - prometheus

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  grafana-data:
