/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IsWithinRadiusRequest } from '../../models/is-within-radius-request';
import { IsWithinRadiusResponse } from '../../models/is-within-radius-response';

export interface IsWithinRadius$Params {
  workSiteId: number;
      body: IsWithinRadiusRequest
}

export function isWithinRadius(http: HttpClient, rootUrl: string, params: IsWithinRadius$Params, context?: HttpContext): Observable<StrictHttpResponse<IsWithinRadiusResponse>> {
  const rb = new RequestBuilder(rootUrl, isWithinRadius.PATH, 'post');
  if (params) {
    rb.path('workSiteId', params.workSiteId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IsWithinRadiusResponse>;
    })
  );
}

isWithinRadius.PATH = '/workSite/{workSiteId}/within-radius';
