/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScheduleInactiveDayRequest } from '../../models/schedule-inactive-day-request';
import { ScheduleInactiveDayResponse } from '../../models/schedule-inactive-day-response';

export interface ScheduleInactiveDay$Params {
  workSiteId: number;
      body: ScheduleInactiveDayRequest
}

export function scheduleInactiveDay(http: HttpClient, rootUrl: string, params: ScheduleInactiveDay$Params, context?: HttpContext): Observable<StrictHttpResponse<ScheduleInactiveDayResponse>> {
  const rb = new RequestBuilder(rootUrl, scheduleInactiveDay.PATH, 'post');
  if (params) {
    rb.path('workSiteId', params.workSiteId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScheduleInactiveDayResponse>;
    })
  );
}

scheduleInactiveDay.PATH = '/workSite/{workSiteId}/inactive-day';
