/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SelectWorkSiteResponse } from '../../models/select-work-site-response';

export interface SelectWorkSite$Params {
  workSiteId: number;
}

export function selectWorkSite(http: HttpClient, rootUrl: string, params: SelectWorkSite$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectWorkSiteResponse>> {
  const rb = new RequestBuilder(rootUrl, selectWorkSite.PATH, 'post');
  if (params) {
    rb.path('workSiteId', params.workSiteId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SelectWorkSiteResponse>;
    })
  );
}

selectWorkSite.PATH = '/workSite/select/{workSiteId}';
