targets:
  $default:
    sources:
      - lib/**
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/api_client/"  # путь к вашему swagger.json
          output_folder: "lib/generated/"