name: face_check
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.8
  built_value: ^8.8.1
  built_collection: ^5.1.1
  one_of_serializer: ^1.0.2
  chopper: ^7.0.9
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  get_it: ^7.6.7
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  provider: ^6.0.0
  flutter_local_notifications: ^15.0.0
  timezone: ^0.9.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  open_filex: ^4.3.2
  local_auth: ^2.1.8
  jwt_decoder: ^2.0.1
  flutter_animate: ^4.5.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  swagger_dart_code_generator: ^2.15.0
  build_runner: ^2.4.8
  built_value_generator: ^8.9.0
  chopper_generator: ^7.0.7
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0
  analyzer: ^6.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/facecheck2.jpg
    - assets/images/facecheck.jpg
    - assets/images/logo.jpg