/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocationRecordDto } from '../../models/location-record-dto';

export interface GetLocationHistory$Params {

/**
 * User ID
 */
  userId: number;

/**
 * Start date (YYYY-MM-DD)
 */
  startDate: string;
}

export function getLocationHistory(http: HttpClient, rootUrl: string, params: GetLocationHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationRecordDto>>> {
  const rb = new RequestBuilder(rootUrl, getLocationHistory.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('startDate', params.startDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LocationRecordDto>>;
    })
  );
}

getLocationHistory.PATH = '/location/history/{userId}';
