/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocationRecordDto } from '../../models/location-record-dto';
import { LocationUpdateDto } from '../../models/location-update-dto';

export interface SaveBatchLocations$Params {

/**
 * User ID
 */
  userId: number;
      body: Array<LocationUpdateDto>
}

export function saveBatchLocations(http: HttpClient, rootUrl: string, params: SaveBatchLocations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationRecordDto>>> {
  const rb = new RequestBuilder(rootUrl, saveBatchLocations.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LocationRecordDto>>;
    })
  );
}

saveBatchLocations.PATH = '/location/batch/{userId}';
