/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BillingResponse } from '../models/billing-response';
import { cancelSubscription } from '../fn/billing-controller/cancel-subscription';
import { CancelSubscription$Params } from '../fn/billing-controller/cancel-subscription';
import { createSubscription } from '../fn/billing-controller/create-subscription';
import { CreateSubscription$Params } from '../fn/billing-controller/create-subscription';
import { createSubscriptionV2 } from '../fn/billing-controller/create-subscription-v-2';
import { CreateSubscriptionV2$Params } from '../fn/billing-controller/create-subscription-v-2';
import { updateSeats } from '../fn/billing-controller/update-seats';
import { UpdateSeats$Params } from '../fn/billing-controller/update-seats';

@Injectable({ providedIn: 'root' })
export class BillingControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateSeats()` */
  static readonly UpdateSeatsPath = '/billing/update-seats/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSeats()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateSeats$Response(params: UpdateSeats$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return updateSeats(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSeats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateSeats(params: UpdateSeats$Params, context?: HttpContext): Observable<{
}> {
    return this.updateSeats$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `cancelSubscription()` */
  static readonly CancelSubscriptionPath = '/billing/cancel/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cancelSubscription()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancelSubscription$Response(params: CancelSubscription$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return cancelSubscription(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cancelSubscription$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancelSubscription(params: CancelSubscription$Params, context?: HttpContext): Observable<{
}> {
    return this.cancelSubscription$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `createSubscription()` */
  static readonly CreateSubscriptionPath = '/billing/activate/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSubscription()` instead.
   *
   * This method doesn't expect any request body.
   */
  createSubscription$Response(params: CreateSubscription$Params, context?: HttpContext): Observable<StrictHttpResponse<BillingResponse>> {
    return createSubscription(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSubscription$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createSubscription(params: CreateSubscription$Params, context?: HttpContext): Observable<BillingResponse> {
    return this.createSubscription$Response(params, context).pipe(
      map((r: StrictHttpResponse<BillingResponse>): BillingResponse => r.body)
    );
  }

  /** Path part for operation `createSubscriptionV2()` */
  static readonly CreateSubscriptionV2Path = '/billing/activate/subscription';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSubscriptionV2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSubscriptionV2$Response(params: CreateSubscriptionV2$Params, context?: HttpContext): Observable<StrictHttpResponse<BillingResponse>> {
    return createSubscriptionV2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSubscriptionV2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSubscriptionV2(params: CreateSubscriptionV2$Params, context?: HttpContext): Observable<BillingResponse> {
    return this.createSubscriptionV2$Response(params, context).pipe(
      map((r: StrictHttpResponse<BillingResponse>): BillingResponse => r.body)
    );
  }

}
