/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ContactSalesFormResponse } from '../models/contact-sales-form-response';
import { createContactForm } from '../fn/contact-sales-controller/create-contact-form';
import { CreateContactForm$Params } from '../fn/contact-sales-controller/create-contact-form';
import { deleteContactForm } from '../fn/contact-sales-controller/delete-contact-form';
import { DeleteContactForm$Params } from '../fn/contact-sales-controller/delete-contact-form';
import { getAllContactForms } from '../fn/contact-sales-controller/get-all-contact-forms';
import { GetAllContactForms$Params } from '../fn/contact-sales-controller/get-all-contact-forms';
import { getContactFormById } from '../fn/contact-sales-controller/get-contact-form-by-id';
import { GetContactFormById$Params } from '../fn/contact-sales-controller/get-contact-form-by-id';
import { PageResponseContactSalesFormResponse } from '../models/page-response-contact-sales-form-response';

@Injectable({ providedIn: 'root' })
export class ContactSalesControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllContactForms()` */
  static readonly GetAllContactFormsPath = '/sales';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllContactForms()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllContactForms$Response(params?: GetAllContactForms$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseContactSalesFormResponse>> {
    return getAllContactForms(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllContactForms$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllContactForms(params?: GetAllContactForms$Params, context?: HttpContext): Observable<PageResponseContactSalesFormResponse> {
    return this.getAllContactForms$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseContactSalesFormResponse>): PageResponseContactSalesFormResponse => r.body)
    );
  }

  /** Path part for operation `createContactForm()` */
  static readonly CreateContactFormPath = '/sales';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createContactForm()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createContactForm$Response(params: CreateContactForm$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactSalesFormResponse>> {
    return createContactForm(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createContactForm$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createContactForm(params: CreateContactForm$Params, context?: HttpContext): Observable<ContactSalesFormResponse> {
    return this.createContactForm$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContactSalesFormResponse>): ContactSalesFormResponse => r.body)
    );
  }

  /** Path part for operation `getContactFormById()` */
  static readonly GetContactFormByIdPath = '/sales/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContactFormById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContactFormById$Response(params: GetContactFormById$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactSalesFormResponse>> {
    return getContactFormById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContactFormById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContactFormById(params: GetContactFormById$Params, context?: HttpContext): Observable<ContactSalesFormResponse> {
    return this.getContactFormById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContactSalesFormResponse>): ContactSalesFormResponse => r.body)
    );
  }

  /** Path part for operation `deleteContactForm()` */
  static readonly DeleteContactFormPath = '/sales/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteContactForm()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteContactForm$Response(params: DeleteContactForm$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteContactForm(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteContactForm$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteContactForm(params: DeleteContactForm$Params, context?: HttpContext): Observable<void> {
    return this.deleteContactForm$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
