/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { sendEmail940F } from '../fn/controller-with-new-methods/send-email-940-f';
import { SendEmail940F$Params } from '../fn/controller-with-new-methods/send-email-940-f';
import { sendEmail940FormScheduleA } from '../fn/controller-with-new-methods/send-email-940-form-schedule-a';
import { SendEmail940FormScheduleA$Params } from '../fn/controller-with-new-methods/send-email-940-form-schedule-a';
import { sendEmail941F } from '../fn/controller-with-new-methods/send-email-941-f';
import { SendEmail941F$Params } from '../fn/controller-with-new-methods/send-email-941-f';
import { sendEmail941Sbf } from '../fn/controller-with-new-methods/send-email-941-sbf';
import { SendEmail941Sbf$Params } from '../fn/controller-with-new-methods/send-email-941-sbf';
import { sendEmailAnnualFutaReport } from '../fn/controller-with-new-methods/send-email-annual-futa-report';
import { SendEmailAnnualFutaReport$Params } from '../fn/controller-with-new-methods/send-email-annual-futa-report';
import { sendEmailCsv } from '../fn/controller-with-new-methods/send-email-csv';
import { SendEmailCsv$Params } from '../fn/controller-with-new-methods/send-email-csv';
import { sendEmailEfw2 } from '../fn/controller-with-new-methods/send-email-efw-2';
import { SendEmailEfw2$Params } from '../fn/controller-with-new-methods/send-email-efw-2';
import { sendEmailFutaCompliance } from '../fn/controller-with-new-methods/send-email-futa-compliance';
import { SendEmailFutaCompliance$Params } from '../fn/controller-with-new-methods/send-email-futa-compliance';
import { sendEmailHr } from '../fn/controller-with-new-methods/send-email-hr';
import { SendEmailHr$Params } from '../fn/controller-with-new-methods/send-email-hr';
import { sendEmailPaystubs } from '../fn/controller-with-new-methods/send-email-paystubs';
import { SendEmailPaystubs$Params } from '../fn/controller-with-new-methods/send-email-paystubs';
import { sendEmailQfr } from '../fn/controller-with-new-methods/send-email-qfr';
import { SendEmailQfr$Params } from '../fn/controller-with-new-methods/send-email-qfr';
import { sendEmailQsf } from '../fn/controller-with-new-methods/send-email-qsf';
import { SendEmailQsf$Params } from '../fn/controller-with-new-methods/send-email-qsf';
import { sendEmailW2F } from '../fn/controller-with-new-methods/send-email-w-2-f';
import { SendEmailW2F$Params } from '../fn/controller-with-new-methods/send-email-w-2-f';
import { sendEmailWpr } from '../fn/controller-with-new-methods/send-email-wpr';
import { SendEmailWpr$Params } from '../fn/controller-with-new-methods/send-email-wpr';
import { updatePunchForWorker } from '../fn/controller-with-new-methods/update-punch-for-worker';
import { UpdatePunchForWorker$Params } from '../fn/controller-with-new-methods/update-punch-for-worker';
import { UpdatePunchForWorkerResponse } from '../models/update-punch-for-worker-response';

@Injectable({ providedIn: 'root' })
export class ControllerWithNewMethodsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updatePunchForWorker()` */
  static readonly UpdatePunchForWorkerPath = '/newMethods/worker/{workerId}/punch';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePunchForWorker()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePunchForWorker$Response(params: UpdatePunchForWorker$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdatePunchForWorkerResponse>> {
    return updatePunchForWorker(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePunchForWorker$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePunchForWorker(params: UpdatePunchForWorker$Params, context?: HttpContext): Observable<UpdatePunchForWorkerResponse> {
    return this.updatePunchForWorker$Response(params, context).pipe(
      map((r: StrictHttpResponse<UpdatePunchForWorkerResponse>): UpdatePunchForWorkerResponse => r.body)
    );
  }

  /** Path part for operation `sendEmailPaystubs()` */
  static readonly SendEmailPaystubsPath = '/newMethods/custom-mail/paystubs/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailPaystubs()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailPaystubs$Response(params: SendEmailPaystubs$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailPaystubs(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailPaystubs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailPaystubs(params: SendEmailPaystubs$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailPaystubs$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailWpr()` */
  static readonly SendEmailWprPath = '/newMethods/custom-mail/WRP/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailWpr()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailWpr$Response(params: SendEmailWpr$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailWpr(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailWpr$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailWpr(params: SendEmailWpr$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailWpr$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailW2F()` */
  static readonly SendEmailW2FPath = '/newMethods/custom-mail/W2F/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailW2F()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailW2F$Response(params: SendEmailW2F$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailW2F(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailW2F$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailW2F(params: SendEmailW2F$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailW2F$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailQsf()` */
  static readonly SendEmailQsfPath = '/newMethods/custom-mail/QSF/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailQsf()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailQsf$Response(params: SendEmailQsf$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailQsf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailQsf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailQsf(params: SendEmailQsf$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailQsf$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailQfr()` */
  static readonly SendEmailQfrPath = '/newMethods/custom-mail/QFR/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailQfr()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailQfr$Response(params: SendEmailQfr$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailQfr(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailQfr$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailQfr(params: SendEmailQfr$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailQfr$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailHr()` */
  static readonly SendEmailHrPath = '/newMethods/custom-mail/HR/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailHr()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailHr$Response(params: SendEmailHr$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailHr(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailHr$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailHr(params: SendEmailHr$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailHr$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailFutaCompliance()` */
  static readonly SendEmailFutaCompliancePath = '/newMethods/custom-mail/FC/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailFutaCompliance()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailFutaCompliance$Response(params: SendEmailFutaCompliance$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailFutaCompliance(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailFutaCompliance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailFutaCompliance(params: SendEmailFutaCompliance$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailFutaCompliance$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailEfw2()` */
  static readonly SendEmailEfw2Path = '/newMethods/custom-mail/EFW2/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailEfw2()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailEfw2$Response(params: SendEmailEfw2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailEfw2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailEfw2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailEfw2(params: SendEmailEfw2$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailEfw2$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailCsv()` */
  static readonly SendEmailCsvPath = '/newMethods/custom-mail/CSV/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailCsv()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailCsv$Response(params: SendEmailCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailCsv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailCsv(params: SendEmailCsv$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmailAnnualFutaReport()` */
  static readonly SendEmailAnnualFutaReportPath = '/newMethods/custom-mail/AFR/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailAnnualFutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailAnnualFutaReport$Response(params: SendEmailAnnualFutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmailAnnualFutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailAnnualFutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmailAnnualFutaReport(params: SendEmailAnnualFutaReport$Params, context?: HttpContext): Observable<void> {
    return this.sendEmailAnnualFutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmail941Sbf()` */
  static readonly SendEmail941SbfPath = '/newMethods/custom-mail/941sb/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmail941Sbf()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail941Sbf$Response(params: SendEmail941Sbf$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmail941Sbf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmail941Sbf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail941Sbf(params: SendEmail941Sbf$Params, context?: HttpContext): Observable<void> {
    return this.sendEmail941Sbf$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmail941F()` */
  static readonly SendEmail941FPath = '/newMethods/custom-mail/941/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmail941F()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail941F$Response(params: SendEmail941F$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmail941F(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmail941F$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail941F(params: SendEmail941F$Params, context?: HttpContext): Observable<void> {
    return this.sendEmail941F$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmail940FormScheduleA()` */
  static readonly SendEmail940FormScheduleAPath = '/newMethods/custom-mail/940ScheduleA/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmail940FormScheduleA()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail940FormScheduleA$Response(params: SendEmail940FormScheduleA$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmail940FormScheduleA(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmail940FormScheduleA$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail940FormScheduleA(params: SendEmail940FormScheduleA$Params, context?: HttpContext): Observable<void> {
    return this.sendEmail940FormScheduleA$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `sendEmail940F()` */
  static readonly SendEmail940FPath = '/newMethods/custom-mail/940/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmail940F()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail940F$Response(params: SendEmail940F$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return sendEmail940F(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmail940F$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sendEmail940F(params: SendEmail940F$Params, context?: HttpContext): Observable<void> {
    return this.sendEmail940F$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
