/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { downloadEfw2FromS3 } from '../fn/e-files-controller/download-efw-2-from-s-3';
import { DownloadEfw2FromS3$Params } from '../fn/e-files-controller/download-efw-2-from-s-3';
import { downloadForm940ScheduleAXmlFromS3 } from '../fn/e-files-controller/download-form-940-schedule-a-xml-from-s-3';
import { DownloadForm940ScheduleAXmlFromS3$Params } from '../fn/e-files-controller/download-form-940-schedule-a-xml-from-s-3';
import { downloadForm940XmlFromS3 } from '../fn/e-files-controller/download-form-940-xml-from-s-3';
import { DownloadForm940XmlFromS3$Params } from '../fn/e-files-controller/download-form-940-xml-from-s-3';
import { downloadHoursReportCsvFromS3 } from '../fn/e-files-controller/download-hours-report-csv-from-s-3';
import { DownloadHoursReportCsvFromS3$Params } from '../fn/e-files-controller/download-hours-report-csv-from-s-3';
import { downloadPayrollSummaryReportCsvFromS3 } from '../fn/e-files-controller/download-payroll-summary-report-csv-from-s-3';
import { DownloadPayrollSummaryReportCsvFromS3$Params } from '../fn/e-files-controller/download-payroll-summary-report-csv-from-s-3';
import { downloadScheduleBXml } from '../fn/e-files-controller/download-schedule-b-xml';
import { DownloadScheduleBXml$Params } from '../fn/e-files-controller/download-schedule-b-xml';
import { downloadTaxSummaryReportCsvFromS3 } from '../fn/e-files-controller/download-tax-summary-report-csv-from-s-3';
import { DownloadTaxSummaryReportCsvFromS3$Params } from '../fn/e-files-controller/download-tax-summary-report-csv-from-s-3';
import { downloadXml } from '../fn/e-files-controller/download-xml';
import { DownloadXml$Params } from '../fn/e-files-controller/download-xml';
import { generateEfw2File } from '../fn/e-files-controller/generate-efw-2-file';
import { GenerateEfw2File$Params } from '../fn/e-files-controller/generate-efw-2-file';
import { generateForm940ScheduleAXml } from '../fn/e-files-controller/generate-form-940-schedule-a-xml';
import { GenerateForm940ScheduleAXml$Params } from '../fn/e-files-controller/generate-form-940-schedule-a-xml';
import { generateForm940Xml } from '../fn/e-files-controller/generate-form-940-xml';
import { GenerateForm940Xml$Params } from '../fn/e-files-controller/generate-form-940-xml';
import { generateHoursReportCsv } from '../fn/e-files-controller/generate-hours-report-csv';
import { GenerateHoursReportCsv$Params } from '../fn/e-files-controller/generate-hours-report-csv';
import { generatePayrollSummaryReportCsv } from '../fn/e-files-controller/generate-payroll-summary-report-csv';
import { GeneratePayrollSummaryReportCsv$Params } from '../fn/e-files-controller/generate-payroll-summary-report-csv';
import { generateScheduleBXml } from '../fn/e-files-controller/generate-schedule-b-xml';
import { GenerateScheduleBXml$Params } from '../fn/e-files-controller/generate-schedule-b-xml';
import { generateTaxSummaryReportCsv } from '../fn/e-files-controller/generate-tax-summary-report-csv';
import { GenerateTaxSummaryReportCsv$Params } from '../fn/e-files-controller/generate-tax-summary-report-csv';
import { generateXml } from '../fn/e-files-controller/generate-xml';
import { GenerateXml$Params } from '../fn/e-files-controller/generate-xml';

@Injectable({ providedIn: 'root' })
export class EFilesControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `generateXml()` */
  static readonly GenerateXmlPath = '/e-file/{companyId}/xml';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateXml()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateXml$Response(params: GenerateXml$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return generateXml(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateXml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateXml(params: GenerateXml$Params, context?: HttpContext): Observable<string> {
    return this.generateXml$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `generateScheduleBXml()` */
  static readonly GenerateScheduleBXmlPath = '/e-file/{companyId}/schedule-b';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateScheduleBXml()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateScheduleBXml$Response(params: GenerateScheduleBXml$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return generateScheduleBXml(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateScheduleBXml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateScheduleBXml(params: GenerateScheduleBXml$Params, context?: HttpContext): Observable<string> {
    return this.generateScheduleBXml$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `downloadXml()` */
  static readonly DownloadXmlPath = '/e-file/{companyId}/download';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadXml()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadXml$Response(params: DownloadXml$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadXml(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadXml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadXml(params: DownloadXml$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadXml$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadScheduleBXml()` */
  static readonly DownloadScheduleBXmlPath = '/e-file/{companyId}/download-schedule-b';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadScheduleBXml()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadScheduleBXml$Response(params: DownloadScheduleBXml$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadScheduleBXml(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadScheduleBXml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadScheduleBXml(params: DownloadScheduleBXml$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadScheduleBXml$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateTaxSummaryReportCsv()` */
  static readonly GenerateTaxSummaryReportCsvPath = '/e-file/summary/taxSummaryReport/{companyId}/csv';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateTaxSummaryReportCsv()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateTaxSummaryReportCsv$Response(params: GenerateTaxSummaryReportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateTaxSummaryReportCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateTaxSummaryReportCsv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateTaxSummaryReportCsv(params: GenerateTaxSummaryReportCsv$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateTaxSummaryReportCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generatePayrollSummaryReportCsv()` */
  static readonly GeneratePayrollSummaryReportCsvPath = '/e-file/summary/payrollReport/{companyId}/csv';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generatePayrollSummaryReportCsv()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePayrollSummaryReportCsv$Response(params: GeneratePayrollSummaryReportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generatePayrollSummaryReportCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generatePayrollSummaryReportCsv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePayrollSummaryReportCsv(params: GeneratePayrollSummaryReportCsv$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generatePayrollSummaryReportCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateHoursReportCsv()` */
  static readonly GenerateHoursReportCsvPath = '/e-file/summary/hoursReport/{companyId}/csv';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateHoursReportCsv()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateHoursReportCsv$Response(params: GenerateHoursReportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateHoursReportCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateHoursReportCsv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateHoursReportCsv(params: GenerateHoursReportCsv$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateHoursReportCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateEfw2File()` */
  static readonly GenerateEfw2FilePath = '/e-file/generate-efw2/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateEfw2File()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateEfw2File$Response(params: GenerateEfw2File$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateEfw2File(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateEfw2File$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateEfw2File(params: GenerateEfw2File$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateEfw2File$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm940ScheduleAXml()` */
  static readonly GenerateForm940ScheduleAXmlPath = '/e-file/generate-940sa-xml/{userId}/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm940ScheduleAXml()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940ScheduleAXml$Response(params: GenerateForm940ScheduleAXml$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm940ScheduleAXml(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm940ScheduleAXml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940ScheduleAXml(params: GenerateForm940ScheduleAXml$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm940ScheduleAXml$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm940Xml()` */
  static readonly GenerateForm940XmlPath = '/e-file/generate-940-xml/{userId}/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm940Xml()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940Xml$Response(params: GenerateForm940Xml$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm940Xml(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm940Xml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940Xml(params: GenerateForm940Xml$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm940Xml$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadTaxSummaryReportCsvFromS3()` */
  static readonly DownloadTaxSummaryReportCsvFromS3Path = '/e-file/download-taxSummaryReport-csv/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadTaxSummaryReportCsvFromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadTaxSummaryReportCsvFromS3$Response(params: DownloadTaxSummaryReportCsvFromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadTaxSummaryReportCsvFromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadTaxSummaryReportCsvFromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadTaxSummaryReportCsvFromS3(params: DownloadTaxSummaryReportCsvFromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadTaxSummaryReportCsvFromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadPayrollSummaryReportCsvFromS3()` */
  static readonly DownloadPayrollSummaryReportCsvFromS3Path = '/e-file/download-payrollSummaryReport-csv/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadPayrollSummaryReportCsvFromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadPayrollSummaryReportCsvFromS3$Response(params: DownloadPayrollSummaryReportCsvFromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadPayrollSummaryReportCsvFromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadPayrollSummaryReportCsvFromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadPayrollSummaryReportCsvFromS3(params: DownloadPayrollSummaryReportCsvFromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadPayrollSummaryReportCsvFromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadHoursReportCsvFromS3()` */
  static readonly DownloadHoursReportCsvFromS3Path = '/e-file/download-hoursReport-csv/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadHoursReportCsvFromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadHoursReportCsvFromS3$Response(params: DownloadHoursReportCsvFromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadHoursReportCsvFromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadHoursReportCsvFromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadHoursReportCsvFromS3(params: DownloadHoursReportCsvFromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadHoursReportCsvFromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadEfw2FromS3()` */
  static readonly DownloadEfw2FromS3Path = '/e-file/download-efw2/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadEfw2FromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadEfw2FromS3$Response(params: DownloadEfw2FromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadEfw2FromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadEfw2FromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadEfw2FromS3(params: DownloadEfw2FromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadEfw2FromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadForm940ScheduleAXmlFromS3()` */
  static readonly DownloadForm940ScheduleAXmlFromS3Path = '/e-file/download-940sa-xml/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadForm940ScheduleAXmlFromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940ScheduleAXmlFromS3$Response(params: DownloadForm940ScheduleAXmlFromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadForm940ScheduleAXmlFromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadForm940ScheduleAXmlFromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940ScheduleAXmlFromS3(params: DownloadForm940ScheduleAXmlFromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadForm940ScheduleAXmlFromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadForm940XmlFromS3()` */
  static readonly DownloadForm940XmlFromS3Path = '/e-file/download-940-xml/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadForm940XmlFromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940XmlFromS3$Response(params: DownloadForm940XmlFromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadForm940XmlFromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadForm940XmlFromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940XmlFromS3(params: DownloadForm940XmlFromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadForm940XmlFromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
