/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { acceptTerms } from '../fn/privacy-and-terms-controller/accept-terms';
import { AcceptTerms$Params } from '../fn/privacy-and-terms-controller/accept-terms';
import { getAll } from '../fn/privacy-and-terms-controller/get-all';
import { GetAll$Params } from '../fn/privacy-and-terms-controller/get-all';
import { getById } from '../fn/privacy-and-terms-controller/get-by-id';
import { GetById$Params } from '../fn/privacy-and-terms-controller/get-by-id';
import { PageResponseTermsOfUseRequestDataResponse } from '../models/page-response-terms-of-use-request-data-response';
import { TermsOfUseRequestDataResponse } from '../models/terms-of-use-request-data-response';

@Injectable({ providedIn: 'root' })
export class PrivacyAndTermsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAll()` */
  static readonly GetAllPath = '/privacy-and-terms';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll$Response(params?: GetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTermsOfUseRequestDataResponse>> {
    return getAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll(params?: GetAll$Params, context?: HttpContext): Observable<PageResponseTermsOfUseRequestDataResponse> {
    return this.getAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseTermsOfUseRequestDataResponse>): PageResponseTermsOfUseRequestDataResponse => r.body)
    );
  }

  /** Path part for operation `acceptTerms()` */
  static readonly AcceptTermsPath = '/privacy-and-terms';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `acceptTerms()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptTerms$Response(params: AcceptTerms$Params, context?: HttpContext): Observable<StrictHttpResponse<TermsOfUseRequestDataResponse>> {
    return acceptTerms(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `acceptTerms$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptTerms(params: AcceptTerms$Params, context?: HttpContext): Observable<TermsOfUseRequestDataResponse> {
    return this.acceptTerms$Response(params, context).pipe(
      map((r: StrictHttpResponse<TermsOfUseRequestDataResponse>): TermsOfUseRequestDataResponse => r.body)
    );
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/privacy-and-terms/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<TermsOfUseRequestDataResponse>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<TermsOfUseRequestDataResponse> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TermsOfUseRequestDataResponse>): TermsOfUseRequestDataResponse => r.body)
    );
  }

}
