/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { completeRandomAttendanceVerification } from '../fn/remote-worker-controller/complete-random-attendance-verification';
import { CompleteRandomAttendanceVerification$Params } from '../fn/remote-worker-controller/complete-random-attendance-verification';
import { getAllVerifications } from '../fn/remote-worker-controller/get-all-verifications';
import { GetAllVerifications$Params } from '../fn/remote-worker-controller/get-all-verifications';
import { getPendingVerification } from '../fn/remote-worker-controller/get-pending-verification';
import { GetPendingVerification$Params } from '../fn/remote-worker-controller/get-pending-verification';
import { getVerificationStats } from '../fn/remote-worker-controller/get-verification-stats';
import { GetVerificationStats$Params } from '../fn/remote-worker-controller/get-verification-stats';
import { PageResponseRemoteVerificationAdminResponse } from '../models/page-response-remote-verification-admin-response';
import { RandonAttendanceVerificationResponse } from '../models/randon-attendance-verification-response';
import { RemoteVerificationStatsResponse } from '../models/remote-verification-stats-response';
import { setWorkerOnPerson } from '../fn/remote-worker-controller/set-worker-on-person';
import { SetWorkerOnPerson$Params } from '../fn/remote-worker-controller/set-worker-on-person';
import { setWorkerRemote } from '../fn/remote-worker-controller/set-worker-remote';
import { SetWorkerRemote$Params } from '../fn/remote-worker-controller/set-worker-remote';

@Injectable({ providedIn: 'root' })
export class RemoteWorkerControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `completeRandomAttendanceVerification()` */
  static readonly CompleteRandomAttendanceVerificationPath = '/remote-worker/random-attendance-verification';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `completeRandomAttendanceVerification()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  completeRandomAttendanceVerification$Response(params: CompleteRandomAttendanceVerification$Params, context?: HttpContext): Observable<StrictHttpResponse<RandonAttendanceVerificationResponse>> {
    return completeRandomAttendanceVerification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `completeRandomAttendanceVerification$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  completeRandomAttendanceVerification(params: CompleteRandomAttendanceVerification$Params, context?: HttpContext): Observable<RandonAttendanceVerificationResponse> {
    return this.completeRandomAttendanceVerification$Response(params, context).pipe(
      map((r: StrictHttpResponse<RandonAttendanceVerificationResponse>): RandonAttendanceVerificationResponse => r.body)
    );
  }

  /** Path part for operation `setWorkerRemote()` */
  static readonly SetWorkerRemotePath = '/remote-worker/set-worker-remote/{workerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setWorkerRemote()` instead.
   *
   * This method doesn't expect any request body.
   */
  setWorkerRemote$Response(params: SetWorkerRemote$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return setWorkerRemote(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setWorkerRemote$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setWorkerRemote(params: SetWorkerRemote$Params, context?: HttpContext): Observable<string> {
    return this.setWorkerRemote$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `setWorkerOnPerson()` */
  static readonly SetWorkerOnPersonPath = '/remote-worker/set-worker-on-person/{workerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setWorkerOnPerson()` instead.
   *
   * This method doesn't expect any request body.
   */
  setWorkerOnPerson$Response(params: SetWorkerOnPerson$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return setWorkerOnPerson(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setWorkerOnPerson$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setWorkerOnPerson(params: SetWorkerOnPerson$Params, context?: HttpContext): Observable<string> {
    return this.setWorkerOnPerson$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getPendingVerification()` */
  static readonly GetPendingVerificationPath = '/remote-worker/pending-verification';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPendingVerification()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPendingVerification$Response(params?: GetPendingVerification$Params, context?: HttpContext): Observable<StrictHttpResponse<RandonAttendanceVerificationResponse>> {
    return getPendingVerification(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPendingVerification$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPendingVerification(params?: GetPendingVerification$Params, context?: HttpContext): Observable<RandonAttendanceVerificationResponse> {
    return this.getPendingVerification$Response(params, context).pipe(
      map((r: StrictHttpResponse<RandonAttendanceVerificationResponse>): RandonAttendanceVerificationResponse => r.body)
    );
  }

  /** Path part for operation `getAllVerifications()` */
  static readonly GetAllVerificationsPath = '/remote-worker/admin/verifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllVerifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVerifications$Response(params?: GetAllVerifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseRemoteVerificationAdminResponse>> {
    return getAllVerifications(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllVerifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllVerifications(params?: GetAllVerifications$Params, context?: HttpContext): Observable<PageResponseRemoteVerificationAdminResponse> {
    return this.getAllVerifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseRemoteVerificationAdminResponse>): PageResponseRemoteVerificationAdminResponse => r.body)
    );
  }

  /** Path part for operation `getVerificationStats()` */
  static readonly GetVerificationStatsPath = '/remote-worker/admin/verifications/stats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVerificationStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVerificationStats$Response(params?: GetVerificationStats$Params, context?: HttpContext): Observable<StrictHttpResponse<RemoteVerificationStatsResponse>> {
    return getVerificationStats(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVerificationStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVerificationStats(params?: GetVerificationStats$Params, context?: HttpContext): Observable<RemoteVerificationStatsResponse> {
    return this.getVerificationStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<RemoteVerificationStatsResponse>): RemoteVerificationStatsResponse => r.body)
    );
  }

}
