/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteReport } from '../fn/report-aws-controller/delete-report';
import { DeleteReport$Params } from '../fn/report-aws-controller/delete-report';
import { downloadReport } from '../fn/report-aws-controller/download-report';
import { DownloadReport$Params } from '../fn/report-aws-controller/download-report';
import { getCompanyReports } from '../fn/report-aws-controller/get-company-reports';
import { GetCompanyReports$Params } from '../fn/report-aws-controller/get-company-reports';
import { getReportsByType } from '../fn/report-aws-controller/get-reports-by-type';
import { GetReportsByType$Params } from '../fn/report-aws-controller/get-reports-by-type';
import { ReportFileDto } from '../models/report-file-dto';
import { viewReport } from '../fn/report-aws-controller/view-report';
import { ViewReport$Params } from '../fn/report-aws-controller/view-report';

@Injectable({ providedIn: 'root' })
export class ReportAwsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `viewReport()` */
  static readonly ViewReportPath = '/aws-reports/view';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `viewReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  viewReport$Response(params: ViewReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return viewReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `viewReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  viewReport(params: ViewReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.viewReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadReport()` */
  static readonly DownloadReportPath = '/aws-reports/download';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadReport$Response(params: DownloadReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadReport(params: DownloadReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `getCompanyReports()` */
  static readonly GetCompanyReportsPath = '/aws-reports/company/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCompanyReports()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompanyReports$Response(params: GetCompanyReports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReportFileDto>>> {
    return getCompanyReports(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCompanyReports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompanyReports(params: GetCompanyReports$Params, context?: HttpContext): Observable<Array<ReportFileDto>> {
    return this.getCompanyReports$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReportFileDto>>): Array<ReportFileDto> => r.body)
    );
  }

  /** Path part for operation `getReportsByType()` */
  static readonly GetReportsByTypePath = '/aws-reports/company/{companyId}/type/{reportType}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReportsByType()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportsByType$Response(params: GetReportsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReportFileDto>>> {
    return getReportsByType(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReportsByType$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportsByType(params: GetReportsByType$Params, context?: HttpContext): Observable<Array<ReportFileDto>> {
    return this.getReportsByType$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReportFileDto>>): Array<ReportFileDto> => r.body)
    );
  }

  /** Path part for operation `deleteReport()` */
  static readonly DeleteReportPath = '/aws-reports';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReport$Response(params: DeleteReport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReport(params: DeleteReport$Params, context?: HttpContext): Observable<void> {
    return this.deleteReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
