/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getSickLeaveInfo } from '../fn/sick-leave-controller/get-sick-leave-info';
import { GetSickLeaveInfo$Params } from '../fn/sick-leave-controller/get-sick-leave-info';
import { SickLeaveInfo } from '../models/sick-leave-info';
import { useSickLeave } from '../fn/sick-leave-controller/use-sick-leave';
import { UseSickLeave$Params } from '../fn/sick-leave-controller/use-sick-leave';

@Injectable({ providedIn: 'root' })
export class SickLeaveControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `useSickLeave()` */
  static readonly UseSickLeavePath = '/sick-leave/use';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `useSickLeave()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  useSickLeave$Response(params: UseSickLeave$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return useSickLeave(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `useSickLeave$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  useSickLeave(params: UseSickLeave$Params, context?: HttpContext): Observable<{
}> {
    return this.useSickLeave$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getSickLeaveInfo()` */
  static readonly GetSickLeaveInfoPath = '/sick-leave/info';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSickLeaveInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSickLeaveInfo$Response(params?: GetSickLeaveInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<SickLeaveInfo>> {
    return getSickLeaveInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSickLeaveInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSickLeaveInfo(params?: GetSickLeaveInfo$Params, context?: HttpContext): Observable<SickLeaveInfo> {
    return this.getSickLeaveInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<SickLeaveInfo>): SickLeaveInfo => r.body)
    );
  }

}
