/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { download941Pdf } from '../fn/taxes-controller/download-941-pdf';
import { Download941Pdf$Params } from '../fn/taxes-controller/download-941-pdf';
import { download941SbPdf } from '../fn/taxes-controller/download-941-sb-pdf';
import { Download941SbPdf$Params } from '../fn/taxes-controller/download-941-sb-pdf';
import { downloadAnnualFutaReport } from '../fn/taxes-controller/download-annual-futa-report';
import { DownloadAnnualFutaReport$Params } from '../fn/taxes-controller/download-annual-futa-report';
import { downloadAnnualSutaReportPdf } from '../fn/taxes-controller/download-annual-suta-report-pdf';
import { DownloadAnnualSutaReportPdf$Params } from '../fn/taxes-controller/download-annual-suta-report-pdf';
import { downloadForm940 } from '../fn/taxes-controller/download-form-940';
import { DownloadForm940$Params } from '../fn/taxes-controller/download-form-940';
import { downloadForm940SaFromS3 } from '../fn/taxes-controller/download-form-940-sa-from-s-3';
import { DownloadForm940SaFromS3$Params } from '../fn/taxes-controller/download-form-940-sa-from-s-3';
import { downloadI9 } from '../fn/taxes-controller/download-i-9';
import { DownloadI9$Params } from '../fn/taxes-controller/download-i-9';
import { downloadPayStub } from '../fn/taxes-controller/download-pay-stub';
import { DownloadPayStub$Params } from '../fn/taxes-controller/download-pay-stub';
import { downloadQuarterlyFutaReport } from '../fn/taxes-controller/download-quarterly-futa-report';
import { DownloadQuarterlyFutaReport$Params } from '../fn/taxes-controller/download-quarterly-futa-report';
import { downloadQuarterlySutaReportPdf } from '../fn/taxes-controller/download-quarterly-suta-report-pdf';
import { DownloadQuarterlySutaReportPdf$Params } from '../fn/taxes-controller/download-quarterly-suta-report-pdf';
import { downloadQuarterlyTaxSummaryPdf } from '../fn/taxes-controller/download-quarterly-tax-summary-pdf';
import { DownloadQuarterlyTaxSummaryPdf$Params } from '../fn/taxes-controller/download-quarterly-tax-summary-pdf';
import { downloadW2FromS3 } from '../fn/taxes-controller/download-w-2-from-s-3';
import { DownloadW2FromS3$Params } from '../fn/taxes-controller/download-w-2-from-s-3';
import { downloadW3FromS3 } from '../fn/taxes-controller/download-w-3-from-s-3';
import { DownloadW3FromS3$Params } from '../fn/taxes-controller/download-w-3-from-s-3';
import { downloadW4Form } from '../fn/taxes-controller/download-w-4-form';
import { DownloadW4Form$Params } from '../fn/taxes-controller/download-w-4-form';
import { generateAnnualFutaReport } from '../fn/taxes-controller/generate-annual-futa-report';
import { GenerateAnnualFutaReport$Params } from '../fn/taxes-controller/generate-annual-futa-report';
import { generateAnnualSutaReport } from '../fn/taxes-controller/generate-annual-suta-report';
import { GenerateAnnualSutaReport$Params } from '../fn/taxes-controller/generate-annual-suta-report';
import { generateForm1040Pdf } from '../fn/taxes-controller/generate-form-1040-pdf';
import { GenerateForm1040Pdf$Params } from '../fn/taxes-controller/generate-form-1040-pdf';
import { generateForm1094CPdf } from '../fn/taxes-controller/generate-form-1094-c-pdf';
import { GenerateForm1094CPdf$Params } from '../fn/taxes-controller/generate-form-1094-c-pdf';
import { generateForm1095BPdf } from '../fn/taxes-controller/generate-form-1095-b-pdf';
import { GenerateForm1095BPdf$Params } from '../fn/taxes-controller/generate-form-1095-b-pdf';
import { generateForm1095CPdf } from '../fn/taxes-controller/generate-form-1095-c-pdf';
import { GenerateForm1095CPdf$Params } from '../fn/taxes-controller/generate-form-1095-c-pdf';
import { generateForm940 } from '../fn/taxes-controller/generate-form-940';
import { GenerateForm940$Params } from '../fn/taxes-controller/generate-form-940';
import { generateForm940Sa } from '../fn/taxes-controller/generate-form-940-sa';
import { GenerateForm940Sa$Params } from '../fn/taxes-controller/generate-form-940-sa';
import { generateForm941Pdf } from '../fn/taxes-controller/generate-form-941-pdf';
import { GenerateForm941Pdf$Params } from '../fn/taxes-controller/generate-form-941-pdf';
import { generateForm941SbPdf } from '../fn/taxes-controller/generate-form-941-sb-pdf';
import { GenerateForm941SbPdf$Params } from '../fn/taxes-controller/generate-form-941-sb-pdf';
import { generateForm941XPdf } from '../fn/taxes-controller/generate-form-941-x-pdf';
import { GenerateForm941XPdf$Params } from '../fn/taxes-controller/generate-form-941-x-pdf';
import { generateFormW4Pdf } from '../fn/taxes-controller/generate-form-w-4-pdf';
import { GenerateFormW4Pdf$Params } from '../fn/taxes-controller/generate-form-w-4-pdf';
import { generateHoursReport } from '../fn/taxes-controller/generate-hours-report';
import { GenerateHoursReport$Params } from '../fn/taxes-controller/generate-hours-report';
import { generatePayrollSummaryReport } from '../fn/taxes-controller/generate-payroll-summary-report';
import { GeneratePayrollSummaryReport$Params } from '../fn/taxes-controller/generate-payroll-summary-report';
import { generatePayStub } from '../fn/taxes-controller/generate-pay-stub';
import { GeneratePayStub$Params } from '../fn/taxes-controller/generate-pay-stub';
import { generateQuarterlyFutaReport } from '../fn/taxes-controller/generate-quarterly-futa-report';
import { GenerateQuarterlyFutaReport$Params } from '../fn/taxes-controller/generate-quarterly-futa-report';
import { generateQuarterlySutaReport } from '../fn/taxes-controller/generate-quarterly-suta-report';
import { GenerateQuarterlySutaReport$Params } from '../fn/taxes-controller/generate-quarterly-suta-report';
import { generateQuarterlyTaxSummaryPdf } from '../fn/taxes-controller/generate-quarterly-tax-summary-pdf';
import { GenerateQuarterlyTaxSummaryPdf$Params } from '../fn/taxes-controller/generate-quarterly-tax-summary-pdf';
import { generateW2Pdf } from '../fn/taxes-controller/generate-w-2-pdf';
import { GenerateW2Pdf$Params } from '../fn/taxes-controller/generate-w-2-pdf';
import { generateW3Pdf } from '../fn/taxes-controller/generate-w-3-pdf';
import { GenerateW3Pdf$Params } from '../fn/taxes-controller/generate-w-3-pdf';
import { getCompanyPayStubFiles } from '../fn/taxes-controller/get-company-pay-stub-files';
import { GetCompanyPayStubFiles$Params } from '../fn/taxes-controller/get-company-pay-stub-files';
import { getGroupedPayStubFiles } from '../fn/taxes-controller/get-grouped-pay-stub-files';
import { GetGroupedPayStubFiles$Params } from '../fn/taxes-controller/get-grouped-pay-stub-files';
import { getWorkerPayStubFiles } from '../fn/taxes-controller/get-worker-pay-stub-files';
import { GetWorkerPayStubFiles$Params } from '../fn/taxes-controller/get-worker-pay-stub-files';
import { getWorkerYearlySummary } from '../fn/taxes-controller/get-worker-yearly-summary';
import { GetWorkerYearlySummary$Params } from '../fn/taxes-controller/get-worker-yearly-summary';
import { PayStubFileDto } from '../models/pay-stub-file-dto';
import { SutaReportDto } from '../models/suta-report-dto';
import { WorkerYearlySummaryDto } from '../models/worker-yearly-summary-dto';

@Injectable({ providedIn: 'root' })
export class TaxesControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getWorkerYearlySummary()` */
  static readonly GetWorkerYearlySummaryPath = '/taxes-forms/worker/{workerId}/year/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWorkerYearlySummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWorkerYearlySummary$Response(params: GetWorkerYearlySummary$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerYearlySummaryDto>> {
    return getWorkerYearlySummary(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWorkerYearlySummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWorkerYearlySummary(params: GetWorkerYearlySummary$Params, context?: HttpContext): Observable<WorkerYearlySummaryDto> {
    return this.getWorkerYearlySummary$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerYearlySummaryDto>): WorkerYearlySummaryDto => r.body)
    );
  }

  /** Path part for operation `generatePayrollSummaryReport()` */
  static readonly GeneratePayrollSummaryReportPath = '/taxes-forms/summary/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generatePayrollSummaryReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePayrollSummaryReport$Response(params: GeneratePayrollSummaryReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generatePayrollSummaryReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generatePayrollSummaryReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePayrollSummaryReport(params: GeneratePayrollSummaryReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generatePayrollSummaryReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateHoursReport()` */
  static readonly GenerateHoursReportPath = '/taxes-forms/summary/hoursReport/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateHoursReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateHoursReport$Response(params: GenerateHoursReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateHoursReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateHoursReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateHoursReport(params: GenerateHoursReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateHoursReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateQuarterlySutaReport()` */
  static readonly GenerateQuarterlySutaReportPath = '/taxes-forms/quarterly/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateQuarterlySutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateQuarterlySutaReport$Response(params: GenerateQuarterlySutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SutaReportDto>> {
    return generateQuarterlySutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateQuarterlySutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateQuarterlySutaReport(params: GenerateQuarterlySutaReport$Params, context?: HttpContext): Observable<SutaReportDto> {
    return this.generateQuarterlySutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<SutaReportDto>): SutaReportDto => r.body)
    );
  }

  /** Path part for operation `downloadQuarterlySutaReportPdf()` */
  static readonly DownloadQuarterlySutaReportPdfPath = '/taxes-forms/quarterly/{companyId}/{year}/{quarter}/pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadQuarterlySutaReportPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadQuarterlySutaReportPdf$Response(params: DownloadQuarterlySutaReportPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadQuarterlySutaReportPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadQuarterlySutaReportPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadQuarterlySutaReportPdf(params: DownloadQuarterlySutaReportPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadQuarterlySutaReportPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `getCompanyPayStubFiles()` */
  static readonly GetCompanyPayStubFilesPath = '/taxes-forms/paystubs/company/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCompanyPayStubFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompanyPayStubFiles$Response(params: GetCompanyPayStubFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PayStubFileDto>>> {
    return getCompanyPayStubFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCompanyPayStubFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompanyPayStubFiles(params: GetCompanyPayStubFiles$Params, context?: HttpContext): Observable<Array<PayStubFileDto>> {
    return this.getCompanyPayStubFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PayStubFileDto>>): Array<PayStubFileDto> => r.body)
    );
  }

  /** Path part for operation `getWorkerPayStubFiles()` */
  static readonly GetWorkerPayStubFilesPath = '/taxes-forms/paystubs/company/{companyId}/worker/{workerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWorkerPayStubFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWorkerPayStubFiles$Response(params: GetWorkerPayStubFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PayStubFileDto>>> {
    return getWorkerPayStubFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWorkerPayStubFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWorkerPayStubFiles(params: GetWorkerPayStubFiles$Params, context?: HttpContext): Observable<Array<PayStubFileDto>> {
    return this.getWorkerPayStubFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PayStubFileDto>>): Array<PayStubFileDto> => r.body)
    );
  }

  /** Path part for operation `getGroupedPayStubFiles()` */
  static readonly GetGroupedPayStubFilesPath = '/taxes-forms/paystubs/company/{companyId}/grouped';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGroupedPayStubFiles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGroupedPayStubFiles$Response(params: GetGroupedPayStubFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: Array<PayStubFileDto>;
}>> {
    return getGroupedPayStubFiles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGroupedPayStubFiles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGroupedPayStubFiles(params: GetGroupedPayStubFiles$Params, context?: HttpContext): Observable<{
[key: string]: Array<PayStubFileDto>;
}> {
    return this.getGroupedPayStubFiles$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: Array<PayStubFileDto>;
}>): {
[key: string]: Array<PayStubFileDto>;
} => r.body)
    );
  }

  /** Path part for operation `downloadI9()` */
  static readonly DownloadI9Path = '/taxes-forms/i9/{userId}/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadI9()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadI9$Response(params: DownloadI9$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadI9(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadI9$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadI9(params: DownloadI9$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadI9$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateFormW4Pdf()` */
  static readonly GenerateFormW4PdfPath = '/taxes-forms/generateW4pdf/{userId}/company/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateFormW4Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateFormW4Pdf$Response(params: GenerateFormW4Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateFormW4Pdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateFormW4Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateFormW4Pdf(params: GenerateFormW4Pdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateFormW4Pdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm941XPdf()` */
  static readonly GenerateForm941XPdfPath = '/taxes-forms/generate941x_pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm941XPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm941XPdf$Response(params?: GenerateForm941XPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm941XPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm941XPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm941XPdf(params?: GenerateForm941XPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm941XPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm1095CPdf()` */
  static readonly GenerateForm1095CPdfPath = '/taxes-forms/generate1095c_pdf/{companyId}/{userId}/{reportYear}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm1095CPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1095CPdf$Response(params: GenerateForm1095CPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm1095CPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm1095CPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1095CPdf(params: GenerateForm1095CPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm1095CPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm1095BPdf()` */
  static readonly GenerateForm1095BPdfPath = '/taxes-forms/generate1095b_pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm1095BPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1095BPdf$Response(params?: GenerateForm1095BPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm1095BPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm1095BPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1095BPdf(params?: GenerateForm1095BPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm1095BPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm1094CPdf()` */
  static readonly GenerateForm1094CPdfPath = '/taxes-forms/generate1094c_pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm1094CPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1094CPdf$Response(params?: GenerateForm1094CPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm1094CPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm1094CPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1094CPdf(params?: GenerateForm1094CPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm1094CPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm1040Pdf()` */
  static readonly GenerateForm1040PdfPath = '/taxes-forms/generate1040_pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm1040Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1040Pdf$Response(params?: GenerateForm1040Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm1040Pdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm1040Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm1040Pdf(params?: GenerateForm1040Pdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm1040Pdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generatePayStub()` */
  static readonly GeneratePayStubPath = '/taxes-forms/generate/{payrollId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generatePayStub()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePayStub$Response(params: GeneratePayStub$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generatePayStub(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generatePayStub$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePayStub(params: GeneratePayStub$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generatePayStub$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateW3Pdf()` */
  static readonly GenerateW3PdfPath = '/taxes-forms/generate-w3/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateW3Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateW3Pdf$Response(params: GenerateW3Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateW3Pdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateW3Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateW3Pdf(params: GenerateW3Pdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateW3Pdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateW2Pdf()` */
  static readonly GenerateW2PdfPath = '/taxes-forms/generate-w2/{workerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateW2Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateW2Pdf$Response(params: GenerateW2Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateW2Pdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateW2Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateW2Pdf(params: GenerateW2Pdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateW2Pdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateQuarterlyTaxSummaryPdf()` */
  static readonly GenerateQuarterlyTaxSummaryPdfPath = '/taxes-forms/generate-tax-summary-quarterly/{companyId}/{year}/{quarter}';

  /**
   * Generate Quarterly Tax Summary Report PDF.
   *
   * Generate and download quarterly tax summary report PDF
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateQuarterlyTaxSummaryPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateQuarterlyTaxSummaryPdf$Response(params: GenerateQuarterlyTaxSummaryPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateQuarterlyTaxSummaryPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * Generate Quarterly Tax Summary Report PDF.
   *
   * Generate and download quarterly tax summary report PDF
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateQuarterlyTaxSummaryPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateQuarterlyTaxSummaryPdf(params: GenerateQuarterlyTaxSummaryPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateQuarterlyTaxSummaryPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateQuarterlyFutaReport()` */
  static readonly GenerateQuarterlyFutaReportPath = '/taxes-forms/generate-quarterly/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateQuarterlyFutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateQuarterlyFutaReport$Response(params: GenerateQuarterlyFutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateQuarterlyFutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateQuarterlyFutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateQuarterlyFutaReport(params: GenerateQuarterlyFutaReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateQuarterlyFutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateAnnualFutaReport()` */
  static readonly GenerateAnnualFutaReportPath = '/taxes-forms/generate-annual/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateAnnualFutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateAnnualFutaReport$Response(params: GenerateAnnualFutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateAnnualFutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateAnnualFutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateAnnualFutaReport(params: GenerateAnnualFutaReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateAnnualFutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm941SbPdf()` */
  static readonly GenerateForm941SbPdfPath = '/taxes-forms/generate-941sb-pdf/{userId}/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm941SbPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm941SbPdf$Response(params: GenerateForm941SbPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm941SbPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm941SbPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm941SbPdf(params: GenerateForm941SbPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm941SbPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm941Pdf()` */
  static readonly GenerateForm941PdfPath = '/taxes-forms/generate-941-pdf/{userId}/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm941Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm941Pdf$Response(params: GenerateForm941Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm941Pdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm941Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm941Pdf(params: GenerateForm941Pdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm941Pdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm940()` */
  static readonly GenerateForm940Path = '/taxes-forms/generate-940/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm940()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940$Response(params: GenerateForm940$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm940(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm940$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940(params: GenerateForm940$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm940$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateForm940Sa()` */
  static readonly GenerateForm940SaPath = '/taxes-forms/generate-940-sa/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateForm940Sa()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940Sa$Response(params: GenerateForm940Sa$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateForm940Sa(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateForm940Sa$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateForm940Sa(params: GenerateForm940Sa$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateForm940Sa$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadW4Form()` */
  static readonly DownloadW4FormPath = '/taxes-forms/download-w4/{companyId}/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadW4Form()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadW4Form$Response(params: DownloadW4Form$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadW4Form(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadW4Form$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadW4Form(params: DownloadW4Form$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadW4Form$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadW3FromS3()` */
  static readonly DownloadW3FromS3Path = '/taxes-forms/download-w3/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadW3FromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadW3FromS3$Response(params: DownloadW3FromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadW3FromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadW3FromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadW3FromS3(params: DownloadW3FromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadW3FromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadW2FromS3()` */
  static readonly DownloadW2FromS3Path = '/taxes-forms/download-w2/{companyId}/{workerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadW2FromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadW2FromS3$Response(params: DownloadW2FromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadW2FromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadW2FromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadW2FromS3(params: DownloadW2FromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadW2FromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadQuarterlyTaxSummaryPdf()` */
  static readonly DownloadQuarterlyTaxSummaryPdfPath = '/taxes-forms/download-tax-summary-quarterly/{companyId}/{year}/{quarter}';

  /**
   * Download Quarterly Tax Summary PDF from S3.
   *
   * Download existing quarterly tax summary report PDF from S3
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadQuarterlyTaxSummaryPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadQuarterlyTaxSummaryPdf$Response(params: DownloadQuarterlyTaxSummaryPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadQuarterlyTaxSummaryPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * Download Quarterly Tax Summary PDF from S3.
   *
   * Download existing quarterly tax summary report PDF from S3
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadQuarterlyTaxSummaryPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadQuarterlyTaxSummaryPdf(params: DownloadQuarterlyTaxSummaryPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadQuarterlyTaxSummaryPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadQuarterlyFutaReport()` */
  static readonly DownloadQuarterlyFutaReportPath = '/taxes-forms/download-quarterly/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadQuarterlyFutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadQuarterlyFutaReport$Response(params: DownloadQuarterlyFutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadQuarterlyFutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadQuarterlyFutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadQuarterlyFutaReport(params: DownloadQuarterlyFutaReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadQuarterlyFutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadPayStub()` */
  static readonly DownloadPayStubPath = '/taxes-forms/download-paystub/{payrollId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadPayStub()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadPayStub$Response(params: DownloadPayStub$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadPayStub(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadPayStub$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadPayStub(params: DownloadPayStub$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadPayStub$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadAnnualFutaReport()` */
  static readonly DownloadAnnualFutaReportPath = '/taxes-forms/download-annual/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadAnnualFutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadAnnualFutaReport$Response(params: DownloadAnnualFutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadAnnualFutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadAnnualFutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadAnnualFutaReport(params: DownloadAnnualFutaReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadAnnualFutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `download941SbPdf()` */
  static readonly Download941SbPdfPath = '/taxes-forms/download-941sb-pdf/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `download941SbPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  download941SbPdf$Response(params: Download941SbPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return download941SbPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `download941SbPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  download941SbPdf(params: Download941SbPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.download941SbPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `download941Pdf()` */
  static readonly Download941PdfPath = '/taxes-forms/download-941-pdf/{companyId}/{year}/{quarter}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `download941Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  download941Pdf$Response(params: Download941Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return download941Pdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `download941Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  download941Pdf(params: Download941Pdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.download941Pdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadForm940SaFromS3()` */
  static readonly DownloadForm940SaFromS3Path = '/taxes-forms/download-940sa/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadForm940SaFromS3()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940SaFromS3$Response(params: DownloadForm940SaFromS3$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadForm940SaFromS3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadForm940SaFromS3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940SaFromS3(params: DownloadForm940SaFromS3$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadForm940SaFromS3$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `downloadForm940()` */
  static readonly DownloadForm940Path = '/taxes-forms/download-940/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadForm940()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940$Response(params: DownloadForm940$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadForm940(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadForm940$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadForm940(params: DownloadForm940$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadForm940$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateAnnualSutaReport()` */
  static readonly GenerateAnnualSutaReportPath = '/taxes-forms/annual/{companyId}/{year}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateAnnualSutaReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateAnnualSutaReport$Response(params: GenerateAnnualSutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SutaReportDto>> {
    return generateAnnualSutaReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateAnnualSutaReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateAnnualSutaReport(params: GenerateAnnualSutaReport$Params, context?: HttpContext): Observable<SutaReportDto> {
    return this.generateAnnualSutaReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<SutaReportDto>): SutaReportDto => r.body)
    );
  }

  /** Path part for operation `downloadAnnualSutaReportPdf()` */
  static readonly DownloadAnnualSutaReportPdfPath = '/taxes-forms/annual/{companyId}/{year}/pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadAnnualSutaReportPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadAnnualSutaReportPdf$Response(params: DownloadAnnualSutaReportPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return downloadAnnualSutaReportPdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadAnnualSutaReportPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadAnnualSutaReportPdf(params: DownloadAnnualSutaReportPdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.downloadAnnualSutaReportPdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
