/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { generateFullYearData } from '../fn/test-data-generator-controller/generate-full-year-data';
import { GenerateFullYearData$Params } from '../fn/test-data-generator-controller/generate-full-year-data';

@Injectable({ providedIn: 'root' })
export class TestDataGeneratorControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `generateFullYearData()` */
  static readonly GenerateFullYearDataPath = '/test-data/generate-full-year';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateFullYearData()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateFullYearData$Response(params?: GenerateFullYearData$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return generateFullYearData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateFullYearData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateFullYearData(params?: GenerateFullYearData$Params, context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.generateFullYearData$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

}
