/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getLastLocation } from '../fn/track-location-controller/get-last-location';
import { GetLastLocation$Params } from '../fn/track-location-controller/get-last-location';
import { getLocationHistory } from '../fn/track-location-controller/get-location-history';
import { GetLocationHistory$Params } from '../fn/track-location-controller/get-location-history';
import { LocationRecordDto } from '../models/location-record-dto';
import { saveBatchLocations } from '../fn/track-location-controller/save-batch-locations';
import { SaveBatchLocations$Params } from '../fn/track-location-controller/save-batch-locations';
import { updateLocation } from '../fn/track-location-controller/update-location';
import { UpdateLocation$Params } from '../fn/track-location-controller/update-location';

@Injectable({ providedIn: 'root' })
export class TrackLocationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateLocation()` */
  static readonly UpdateLocationPath = '/location/update/{userId}';

  /**
   * Update user location.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateLocation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLocation$Response(params: UpdateLocation$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return updateLocation(this.http, this.rootUrl, params, context);
  }

  /**
   * Update user location.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateLocation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateLocation(params: UpdateLocation$Params, context?: HttpContext): Observable<string> {
    return this.updateLocation$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `saveBatchLocations()` */
  static readonly SaveBatchLocationsPath = '/location/batch/{userId}';

  /**
   * Save batch locations.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveBatchLocations()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBatchLocations$Response(params: SaveBatchLocations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationRecordDto>>> {
    return saveBatchLocations(this.http, this.rootUrl, params, context);
  }

  /**
   * Save batch locations.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveBatchLocations$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBatchLocations(params: SaveBatchLocations$Params, context?: HttpContext): Observable<Array<LocationRecordDto>> {
    return this.saveBatchLocations$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LocationRecordDto>>): Array<LocationRecordDto> => r.body)
    );
  }

  /** Path part for operation `getLastLocation()` */
  static readonly GetLastLocationPath = '/location/last/{userId}';

  /**
   * Get last location for user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLastLocation()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLastLocation$Response(params: GetLastLocation$Params, context?: HttpContext): Observable<StrictHttpResponse<LocationRecordDto>> {
    return getLastLocation(this.http, this.rootUrl, params, context);
  }

  /**
   * Get last location for user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLastLocation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLastLocation(params: GetLastLocation$Params, context?: HttpContext): Observable<LocationRecordDto> {
    return this.getLastLocation$Response(params, context).pipe(
      map((r: StrictHttpResponse<LocationRecordDto>): LocationRecordDto => r.body)
    );
  }

  /** Path part for operation `getLocationHistory()` */
  static readonly GetLocationHistoryPath = '/location/history/{userId}';

  /**
   * Get location history for user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLocationHistory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLocationHistory$Response(params: GetLocationHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationRecordDto>>> {
    return getLocationHistory(this.http, this.rootUrl, params, context);
  }

  /**
   * Get location history for user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLocationHistory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLocationHistory(params: GetLocationHistory$Params, context?: HttpContext): Observable<Array<LocationRecordDto>> {
    return this.getLocationHistory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LocationRecordDto>>): Array<LocationRecordDto> => r.body)
    );
  }

}
