/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/wc-risk-class-controller/create';
import { Create$Params } from '../fn/wc-risk-class-controller/create';
import { delete$ } from '../fn/wc-risk-class-controller/delete';
import { Delete$Params } from '../fn/wc-risk-class-controller/delete';
import { generateCsv } from '../fn/wc-risk-class-controller/generate-csv';
import { GenerateCsv$Params } from '../fn/wc-risk-class-controller/generate-csv';
import { generatePdf } from '../fn/wc-risk-class-controller/generate-pdf';
import { GeneratePdf$Params } from '../fn/wc-risk-class-controller/generate-pdf';
import { getByCode } from '../fn/wc-risk-class-controller/get-by-code';
import { GetByCode$Params } from '../fn/wc-risk-class-controller/get-by-code';
import { list } from '../fn/wc-risk-class-controller/list';
import { List$Params } from '../fn/wc-risk-class-controller/list';
import { PageResponseWcRiskResponse } from '../models/page-response-wc-risk-response';
import { update } from '../fn/wc-risk-class-controller/update';
import { Update$Params } from '../fn/wc-risk-class-controller/update';
import { WcRiskResponse } from '../models/wc-risk-response';

@Injectable({ providedIn: 'root' })
export class WcRiskClassControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getByCode()` */
  static readonly GetByCodePath = '/wc-classes/{code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getByCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCode$Response(params: GetByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<WcRiskResponse>> {
    return getByCode(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getByCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCode(params: GetByCode$Params, context?: HttpContext): Observable<WcRiskResponse> {
    return this.getByCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<WcRiskResponse>): WcRiskResponse => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/wc-classes/{code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<WcRiskResponse>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<WcRiskResponse> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<WcRiskResponse>): WcRiskResponse => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/wc-classes/{code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `list()` */
  static readonly ListPath = '/wc-classes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `list()` instead.
   *
   * This method doesn't expect any request body.
   */
  list$Response(params?: List$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseWcRiskResponse>> {
    return list(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `list$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  list(params?: List$Params, context?: HttpContext): Observable<PageResponseWcRiskResponse> {
    return this.list$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseWcRiskResponse>): PageResponseWcRiskResponse => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/wc-classes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<WcRiskResponse>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<WcRiskResponse> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<WcRiskResponse>): WcRiskResponse => r.body)
    );
  }

  /** Path part for operation `generatePdf()` */
  static readonly GeneratePdfPath = '/wc-classes/pdf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generatePdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePdf$Response(params: GeneratePdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generatePdf(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generatePdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generatePdf(params: GeneratePdf$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generatePdf$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `generateCsv()` */
  static readonly GenerateCsvPath = '/wc-classes/csv';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateCsv()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateCsv$Response(params: GenerateCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateCsv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateCsv(params: GenerateCsv$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
