/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { generateYtdReport } from '../fn/year-to-date-custom-report-controller/generate-ytd-report';
import { GenerateYtdReport$Params } from '../fn/year-to-date-custom-report-controller/generate-ytd-report';

@Injectable({ providedIn: 'root' })
export class YearToDateCustomReportControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `generateYtdReport()` */
  static readonly GenerateYtdReportPath = '/ytd/generate/{companyId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateYtdReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateYtdReport$Response(params: GenerateYtdReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return generateYtdReport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateYtdReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateYtdReport(params: GenerateYtdReport$Params, context?: HttpContext): Observable<Array<string>> {
    return this.generateYtdReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
