/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { WcRiskClassControllerService } from './services/wc-risk-class-controller.service';
import { UserServiceControllerService } from './services/user-service-controller.service';
import { ControllerWithNewMethodsService } from './services/controller-with-new-methods.service';
import { CompanyControllerService } from './services/company-controller.service';
import { AuthenticationService } from './services/authentication.service';
import { AdminControllerService } from './services/admin-controller.service';
import { WorkSiteControllerService } from './services/work-site-controller.service';
import { TestDataGeneratorControllerService } from './services/test-data-generator-controller.service';
import { SickLeaveControllerService } from './services/sick-leave-controller.service';
import { WorkScheduleControllerService } from './services/work-schedule-controller.service';
import { ContactSalesControllerService } from './services/contact-sales-controller.service';
import { PrivacyAndTermsControllerService } from './services/privacy-and-terms-controller.service';
import { PaymentHistoryIrsControllerService } from './services/payment-history-irs-controller.service';
import { NotificationControllerService } from './services/notification-controller.service';
import { TrackLocationControllerService } from './services/track-location-controller.service';
import { FileControllerService } from './services/file-controller.service';
import { StripeWebhookControllerService } from './services/stripe-webhook-controller.service';
import { BillingControllerService } from './services/billing-controller.service';
import { WorkerAttendanceControllerService } from './services/worker-attendance-controller.service';
import { YearToDateCustomReportControllerService } from './services/year-to-date-custom-report-controller.service';
import { W2ControllerService } from './services/w-2-controller.service';
import { TaxesControllerService } from './services/taxes-controller.service';
import { EFilesControllerService } from './services/e-files-controller.service';
import { ReportAwsControllerService } from './services/report-aws-controller.service';
import { CustomErrorControllerService } from './services/custom-error-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    WcRiskClassControllerService,
    UserServiceControllerService,
    ControllerWithNewMethodsService,
    CompanyControllerService,
    AuthenticationService,
    AdminControllerService,
    WorkSiteControllerService,
    TestDataGeneratorControllerService,
    SickLeaveControllerService,
    WorkScheduleControllerService,
    ContactSalesControllerService,
    PrivacyAndTermsControllerService,
    PaymentHistoryIrsControllerService,
    NotificationControllerService,
    TrackLocationControllerService,
    FileControllerService,
    StripeWebhookControllerService,
    BillingControllerService,
    WorkerAttendanceControllerService,
    YearToDateCustomReportControllerService,
    W2ControllerService,
    TaxesControllerService,
    EFilesControllerService,
    ReportAwsControllerService,
    CustomErrorControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
