/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactSalesFormRequest } from '../../models/contact-sales-form-request';
import { ContactSalesFormResponse } from '../../models/contact-sales-form-response';

export interface CreateContactForm$Params {
      body: ContactSalesFormRequest
}

export function createContactForm(http: HttpClient, rootUrl: string, params: CreateContactForm$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactSalesFormResponse>> {
  const rb = new RequestBuilder(rootUrl, createContactForm.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactSalesFormResponse>;
    })
  );
}

createContactForm.PATH = '/sales';
