/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangePunchOutForWorkerResponse } from '../../models/change-punch-out-for-worker-response';
import { ChangePunchOutRequest } from '../../models/change-punch-out-request';

export interface ChangePunchOutForWorker$Params {
  workerId: number;
      body: ChangePunchOutRequest
}

export function changePunchOutForWorker(http: HttpClient, rootUrl: string, params: ChangePunchOutForWorker$Params, context?: HttpContext): Observable<StrictHttpResponse<ChangePunchOutForWorkerResponse>> {
  const rb = new RequestBuilder(rootUrl, changePunchOutForWorker.PATH, 'post');
  if (params) {
    rb.path('workerId', params.workerId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChangePunchOutForWorkerResponse>;
    })
  );
}

changePunchOutForWorker.PATH = '/admin/worker/{workerId}/punch-out';
