/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChangePunchInForWorkerResponse } from '../../models/change-punch-in-for-worker-response';
import { ChangePunchInRequest } from '../../models/change-punch-in-request';

export interface ChangePunchInForWorker$Params {
  workerId: number;
      body: ChangePunchInRequest
}

export function changePunchInForWorker(http: HttpClient, rootUrl: string, params: ChangePunchInForWorker$Params, context?: HttpContext): Observable<StrictHttpResponse<ChangePunchInForWorkerResponse>> {
  const rb = new RequestBuilder(rootUrl, changePunchInForWorker.PATH, 'post');
  if (params) {
    rb.path('workerId', params.workerId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChangePunchInForWorkerResponse>;
    })
  );
}

changePunchInForWorker.PATH = '/admin/worker/{workerId}/punch-in';
