/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseWorksiteWorkerResponse } from '../../models/page-response-worksite-worker-response';

export interface GetWorkersInWorksite$Params {
  page?: number;
  size?: number;
  worksiteId: number;
}

export function getWorkersInWorksite(http: HttpClient, rootUrl: string, params: GetWorkersInWorksite$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseWorksiteWorkerResponse>> {
  const rb = new RequestBuilder(rootUrl, getWorkersInWorksite.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('worksiteId', params.worksiteId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseWorksiteWorkerResponse>;
    })
  );
}

getWorkersInWorksite.PATH = '/admin/employee';
