/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GenerateForm940ScheduleAXml$Params {
  userId: number;
  companyId: number;
  year: number;
}

export function generateForm940ScheduleAXml(http: HttpClient, rootUrl: string, params: GenerateForm940ScheduleAXml$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
  const rb = new RequestBuilder(rootUrl, generateForm940ScheduleAXml.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('companyId', params.companyId, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<string>>;
    })
  );
}

generateForm940ScheduleAXml.PATH = '/e-file/generate-940sa-xml/{userId}/{companyId}/{year}';
