/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GenerateTaxSummaryReportCsv$Params {
  companyId: number;
  startDate: string;
  endDate: string;
}

export function generateTaxSummaryReportCsv(http: HttpClient, rootUrl: string, params: GenerateTaxSummaryReportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
  const rb = new RequestBuilder(rootUrl, generateTaxSummaryReportCsv.PATH, 'get');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<string>>;
    })
  );
}

generateTaxSummaryReportCsv.PATH = '/e-file/summary/taxSummaryReport/{companyId}/csv';
