/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadQuarterlyFutaReport$Params {
  companyId: number;
  year: number;
  quarter: number;
}

export function downloadQuarterlyFutaReport(http: HttpClient, rootUrl: string, params: DownloadQuarterlyFutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
  const rb = new RequestBuilder(rootUrl, downloadQuarterlyFutaReport.PATH, 'get');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.path('year', params.year, {});
    rb.path('quarter', params.quarter, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<string>>;
    })
  );
}

downloadQuarterlyFutaReport.PATH = '/taxes-forms/download-quarterly/{companyId}/{year}/{quarter}';
