/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SutaReportDto } from '../../models/suta-report-dto';

export interface GenerateAnnualSutaReport$Params {
  companyId: number;
  year: number;
}

export function generateAnnualSutaReport(http: HttpClient, rootUrl: string, params: GenerateAnnualSutaReport$Params, context?: HttpContext): Observable<StrictHttpResponse<SutaReportDto>> {
  const rb = new RequestBuilder(rootUrl, generateAnnualSutaReport.PATH, 'get');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SutaReportDto>;
    })
  );
}

generateAnnualSutaReport.PATH = '/taxes-forms/annual/{companyId}/{year}';
