/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkerYearlySummaryDto } from '../../models/worker-yearly-summary-dto';

export interface GetWorkerYearlySummary$Params {
  workerId: number;
  year: number;
}

export function getWorkerYearlySummary(http: HttpClient, rootUrl: string, params: GetWorkerYearlySummary$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerYearlySummaryDto>> {
  const rb = new RequestBuilder(rootUrl, getWorkerYearlySummary.PATH, 'get');
  if (params) {
    rb.path('workerId', params.workerId, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkerYearlySummaryDto>;
    })
  );
}

getWorkerYearlySummary.PATH = '/taxes-forms/worker/{workerId}/year/{year}';
