/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistrationRequestEmployeeAppOwner } from '../../models/registration-request-employee-app-owner';

export interface RegisterEmployeeFromAppOwnerPage$Params {
      body: RegistrationRequestEmployeeAppOwner
}

export function registerEmployeeFromAppOwnerPage(http: HttpClient, rootUrl: string, params: RegisterEmployeeFromAppOwnerPage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, registerEmployeeFromAppOwnerPage.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

registerEmployeeFromAppOwnerPage.PATH = '/auth/register/employee/app-owner';
