/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsEmailRequest } from '../../models/settings-email-request';
import { SettingsEmailResponse } from '../../models/settings-email-response';

export interface UpdateEmail1$Params {
      body: SettingsEmailRequest
}

export function updateEmail1(http: HttpClient, rootUrl: string, params: UpdateEmail1$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsEmailResponse>> {
  const rb = new RequestBuilder(rootUrl, updateEmail1.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsEmailResponse>;
    })
  );
}

updateEmail1.PATH = '/auth/email';
