/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsPhoneNumberRequest } from '../../models/settings-phone-number-request';
import { SettingsPhoneNumberResponse } from '../../models/settings-phone-number-response';

export interface UpdatePhoneNumber$Params {
      body: SettingsPhoneNumberRequest
}

export function updatePhoneNumber(http: HttpClient, rootUrl: string, params: UpdatePhoneNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsPhoneNumberResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePhoneNumber.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsPhoneNumberResponse>;
    })
  );
}

updatePhoneNumber.PATH = '/auth/phone';
