/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPhoneNumberResponse } from '../../models/user-phone-number-response';

export interface FindWorkerPhoneNumber$Params {
}

export function findWorkerPhoneNumber(http: HttpClient, rootUrl: string, params?: FindWorkerPhoneNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPhoneNumberResponse>> {
  const rb = new RequestBuilder(rootUrl, findWorkerPhoneNumber.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPhoneNumberResponse>;
    })
  );
}

findWorkerPhoneNumber.PATH = '/user/phone';
