/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserFullNameResponse } from '../../models/user-full-name-response';

export interface FindWorkerFullName$Params {
}

export function findWorkerFullName(http: HttpClient, rootUrl: string, params?: FindWorkerFullName$Params, context?: HttpContext): Observable<StrictHttpResponse<UserFullNameResponse>> {
  const rb = new RequestBuilder(rootUrl, findWorkerFullName.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserFullNameResponse>;
    })
  );
}

findWorkerFullName.PATH = '/user/full-name';
