/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserCompanyEmailResponse } from '../../models/user-company-email-response';

export interface FindWorkerCompanyEmail$Params {
}

export function findWorkerCompanyEmail(http: HttpClient, rootUrl: string, params?: FindWorkerCompanyEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<UserCompanyEmailResponse>> {
  const rb = new RequestBuilder(rootUrl, findWorkerCompanyEmail.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserCompanyEmailResponse>;
    })
  );
}

findWorkerCompanyEmail.PATH = '/user/company/email';
