/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserIdResponse } from '../../models/user-id-response';

export interface FindWorkerId$Params {
}

export function findWorkerId(http: HttpClient, rootUrl: string, params?: FindWorkerId$Params, context?: HttpContext): Observable<StrictHttpResponse<UserIdResponse>> {
  const rb = new RequestBuilder(rootUrl, findWorkerId.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserIdResponse>;
    })
  );
}

findWorkerId.PATH = '/user/find-user-id';
