/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddOvertimeRequest } from '../../models/add-overtime-request';
import { OvertimeResponse } from '../../models/overtime-response';

export interface AddManualOvertime$Params {
      body: AddOvertimeRequest
}

export function addManualOvertime(http: HttpClient, rootUrl: string, params: AddManualOvertime$Params, context?: HttpContext): Observable<StrictHttpResponse<OvertimeResponse>> {
  const rb = new RequestBuilder(rootUrl, addManualOvertime.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OvertimeResponse>;
    })
  );
}

addManualOvertime.PATH = '/attendance/overtime/add';
