/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkerPhotosResponse } from '../../models/worker-photos-response';

export interface GetWorkerPhotosByDate$Params {
  workerId: number;
  date: string;
}

export function getWorkerPhotosByDate(http: HttpClient, rootUrl: string, params: GetWorkerPhotosByDate$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerPhotosResponse>> {
  const rb = new RequestBuilder(rootUrl, getWorkerPhotosByDate.PATH, 'get');
  if (params) {
    rb.path('workerId', params.workerId, {});
    rb.query('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkerPhotosResponse>;
    })
  );
}

getWorkerPhotosByDate.PATH = '/attendance/photos/{workerId}';
