package com.zikpak.facecheck.taxesServices.customReportsForCompanys.futaCustomTaxReport;


import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.zikpak.facecheck.entity.Company;
import com.zikpak.facecheck.repository.CompanyRepository;
import com.zikpak.facecheck.repository.EmployerTaxRecordRepository;
import com.zikpak.facecheck.services.amazonS3Service.AmazonS3Service;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import com.itextpdf.kernel.color.Color;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import com.zikpak.facecheck.entity.EmployerTaxRecord;


import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.Month;
import java.util.*;
@Service
@RequiredArgsConstructor
public class FutaQuarterlyReportService {




    private final CompanyRepository companyRepository;
    private final EmployerTaxRecordRepository taxRecordRepository;
    private final AmazonS3Service amazonS3Service;

    public byte[] generateFutaQuarterlyReport(Integer companyId, int year, int quarter) throws Exception {
        Company company = companyRepository.findById(companyId).orElseThrow();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(out);
        PdfDocument pdf = new PdfDocument(writer);
        Document doc = new Document(pdf);

        PdfFont font = PdfFontFactory.createFont("Helvetica-Bold");
        Paragraph header = new Paragraph("FUTA Quarterly Report - Q" + quarter + ", " + year)
                .setFont(font)
                .setFontSize(16)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20);

        doc.add(header);

        Paragraph companyInfo = new Paragraph(String.format(
                "Company: %s\nEIN: %s\nAddress: %s, %s, %s %s",
                company.getCompanyName(),
                company.getEmployerEIN(),
                company.getCompanyAddress(),
                company.getCompanyCity(),
                company.getCompanyState(),
                company.getCompanyZipCode()
        )).setFontSize(10).setMarginBottom(10);

        doc.add(companyInfo);

        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 3, 3, 3}))
                .useAllAvailableWidth();

        table.addHeaderCell(new Cell().add(new Paragraph("Employee ID")).setBackgroundColor(Color.LIGHT_GRAY));
        table.addHeaderCell(new Cell().add(new Paragraph("Employee Name")).setBackgroundColor(Color.LIGHT_GRAY));
        table.addHeaderCell(new Cell().add(new Paragraph("Taxable Wages")));
        table.addHeaderCell(new Cell().add(new Paragraph("FUTA Tax @ 0.6%")));

        Map<Integer, BigDecimal> wagesPerEmployee = getQuarterFutaTaxableWages(companyId, year, quarter);

        BigDecimal totalWages = BigDecimal.ZERO;
        BigDecimal totalFutaTax = BigDecimal.ZERO;

        for (Map.Entry<Integer, BigDecimal> entry : wagesPerEmployee.entrySet()) {
            Integer empId = entry.getKey();
            BigDecimal wages = entry.getValue();
            BigDecimal futaTax = wages.multiply(new BigDecimal("0.006")).setScale(2);
            totalWages = totalWages.add(wages);
            totalFutaTax = totalFutaTax.add(futaTax);

            table.addCell(empId.toString());
            table.addCell("Worker #" + empId); // Заменить на имя, если есть доступ
            table.addCell("$" + wages);
            table.addCell("$" + futaTax);
        }

        table.addCell(new Cell(1, 2).add(new Paragraph("TOTAL")).setBold());
        table.addCell("$" + totalWages);
        table.addCell("$" + totalFutaTax);

        doc.add(table);

        Paragraph footer = new Paragraph("Generated by FaceCheck - FUTA Compliance Report")
                .setFontSize(9)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(30);

        doc.add(footer);

        doc.close();

        String key = String.format("%s/%d/futa/quarterly/futa_q%d_%d.pdf",
                company.getCompanyName().replaceAll("[^A-Za-z0-9]+", "_"),
                companyId, quarter, year);

        amazonS3Service.uploadPdfToS3(out.toByteArray(), key);

        return out.toByteArray();
    }

    private Map<Integer, BigDecimal> getQuarterFutaTaxableWages(Integer companyId, int year, int quarter) {
        LocalDate start = switch (quarter) {
            case 1 -> LocalDate.of(year, Month.JANUARY, 1);
            case 2 -> LocalDate.of(year, Month.APRIL, 1);
            case 3 -> LocalDate.of(year, Month.JULY, 1);
            case 4 -> LocalDate.of(year, Month.OCTOBER, 1);
            default -> throw new IllegalArgumentException("Quarter must be 1–4");
        };
        LocalDate end = start.plusMonths(3).minusDays(1);

        List<EmployerTaxRecord> records = taxRecordRepository.findByCompanyIdAndPeriodStartGreaterThanEqualAndPeriodEndLessThanEqual(companyId, start, end);

        Map<Integer, BigDecimal> empToWages = new HashMap<>();
        for (EmployerTaxRecord r : records) {
            int empId = r.getEmployee().getId();
            BigDecimal ytd = taxRecordRepository.sumFutaTaxableWagesByEmployeeAndYear(empId, year);
            if (ytd.compareTo(new BigDecimal("7000")) >= 0) continue;

            BigDecimal curr = empToWages.getOrDefault(empId, BigDecimal.ZERO);
            BigDecimal total = curr.add(r.getGrossPay());
            BigDecimal available = new BigDecimal("7000").subtract(ytd.subtract(r.getGrossPay()));

            empToWages.put(empId, total.min(available));
        }
        return empToWages;
    }
}
