/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportFileDto } from '../../models/report-file-dto';

export interface GetReportsByType$Params {
  companyId: number;
  reportType: string;
  companyName: string;
}

export function getReportsByType(http: HttpClient, rootUrl: string, params: GetReportsByType$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReportFileDto>>> {
  const rb = new RequestBuilder(rootUrl, getReportsByType.PATH, 'get');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.path('reportType', params.reportType, {});
    rb.query('companyName', params.companyName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReportFileDto>>;
    })
  );
}

getReportsByType.PATH = '/aws-reports/company/{companyId}/type/{reportType}';
