/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PhotoResponse } from '../../models/photo-response';

export interface GetWorkersAttendancePhoto$Params {
  workerId: number;
}

export function getWorkersAttendancePhoto(http: HttpClient, rootUrl: string, params: GetWorkersAttendancePhoto$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PhotoResponse>>> {
  const rb = new RequestBuilder(rootUrl, getWorkersAttendancePhoto.PATH, 'get');
  if (params) {
    rb.path('workerId', params.workerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PhotoResponse>>;
    })
  );
}

getWorkersAttendancePhoto.PATH = '/files/worker/{workerId}/photos';
